### ISSUE TITLE
Parameter 예외 케이스 지원

### ISSUE THREAD

**Issue by Rebwon** [JavaUnit/AutoParams#110]
#101 문제 상황이 재현이 되지 않습니다.

Spring Bean은 interface, abstract class type도 Bean으로 등록이 되는데요. autoparams는 interface와 abstract이 지원되는 타입이 아닌 상황입니다.

Spring Autowired와 호환될 수 있도록 파라미터에 애노테이션이 있다면 예외 상황으로써 다른 동작이 될 수 있도록 하는게 어떨까요?

**Comment by jwChung** [comment]
의견 감사합니다. 라벨 규칙 #24 에 따라 구현 확정되기 전에는 question 라벨 달아 두겠습니다.

**Comment by gyuwon** [comment]
@Rebwon 코드를 사용해서 구체적인 예시를 들어주시면 이해가 쉬울 것 같습니다.

**Comment by Rebwon** [comment]
#101 이슈에 나온 예시 코드와 똑같이 테스트를 재현하면, initializedError 발생과 함께, ObjectGenerationException이 발생합니다.
Spring Boot를 사용해서 Test Context가 실행되기 전에 Junit5 에러가 먼저 발생하기 때문에, #101 의 ParameterResolutionException이 발생하지 않습니다.

아래와 같이 #101 에서 기대하는 ParameterResolutionException이 발생하도록 예시를 작성해봤습니다. 
```java
// AutoArgumentsProvider class
private Object createArgument(Parameter parameter) {
    if (hasAnnotations(parameter)) {
        return null;
    } else {
        ObjectQuery query = ObjectQuery.create(parameter);
        return context.generate(query);
    }
}

private boolean hasAnnotations(Parameter parameter) {
    return stream(parameter.getDeclaredAnnotations()).findFirst().isPresent();
}

@ParameterizedTest
@AutoSource
void sut_parameter_has_annotations_return_null(
    String s1, @Autowired SampleService sampleService, @Autowired SampleService sampleService1) {
    assertThat(s1).isNotNull();
    assertThat(sampleService).isNull();
    assertThat(sampleService1).isNull();
}

interface SampleService {}

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.PARAMETER)
@interface Autowired {}
```

**Comment by gyuwon** [comment]
아 제가 아직 스프링을 쓰고있지 않아서 잘 모르겠네요. @jwChung @mhyeon-lee 도와주십시오.

**Comment by Rebwon** [comment]
@gyuwon Spring Bean 주입을 위해서 파라미터에 특정 annotation이 존재할 경우, 해당 파라미터는 AutoArgumentsProvider에서 예외적으로 null을 return 하도록 하는 제안이었습니다. 혹시 다른 방법이 있는지는 고려해보지 않아서 논의가 필요합니다.

**Comment by gyuwon** [comment]
`null`이 반환되면 해결되는 문제인가요?

**Comment by Rebwon** [comment]
@gyuwon 네 현재까지는 null이 반환되면 해결될 문제입니다.

**Comment by gyuwon** [comment]
@Rebwon 이유를 설명해 주실 수 있을까요?

**Comment by Rebwon** [comment]
@gyuwon #101 에서 기대하는 호환을 위해선, interface, abstract로 만들어진 Spring Bean도 주입 가능해야 합니다. AutoParams에선 현재 interface와 abstract 개체를 지원하고 있지 않기 때문에, ObjectGenerationException이 발생하는 것은 당연한 동작입니다. 다만 Autowired와 같은 annotation이 붙은 파라미터에 대해서는 Spring과의 호환을 위해서 예외적으로 null을 return하면, 이후에 Spring Test Context가 Autowired가 붙은 곳에 DI 해주기 때문에 필요한 동작이라고 생각합니다.

**Comment by gyuwon** [comment]
@Rebwon 제 질문은, `null` 인자에 대해 어떤 과정을 통해 Spring Test Context가 해결해주는가 입니다. 직접 실행해 보셨거나 Spring 코드를 확인하신 건가요?

**Comment by Rebwon** [comment]
@gyuwon https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/test/context/support/DependencyInjectionTestExecutionListener.html 현재까지는 DependencyInjectionTestExecutionListener가 테스트 실행 클래스의 field나 setter method에 한해서만 DI를 지원하고 있습니다. 그래서 #101 의 호환이 필요한 거 같습니다.

**Comment by gyuwon** [comment]
@Rebwon 다시 제 질문을 설명드리면, AutoParams가 특정 인자를 `null`로 설정하면 발생하는 문제가 해결된다는 확실한 근거가 있는가 입니다. 저는 보여주신 문서를 읽어서는 #101 에서 언급된 `matchingResolvers.size()`가 1이 되는지 모르겠습니다.

https://github.com/junit-team/junit5/blob/main/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/execution/ExecutableInvoker.java#L210

저는 아닐 것 같습니다. 왜냐면 `(matchingResolvers.size()`를 확인한 후에 `extensionContext`를 사용해 `Object value = resolver.resolveParameter(parameterContext, extensionContext);` 코드를 실행하기 때문입니다. 물론 저도 직접 해본 것은 아니라 추측입니다. 그래서 그 방식이 확신을 가질만한 근거가 있는지 어쭤보는 거에요.

**Comment by Rebwon** [comment]
@gyuwon 

아래와 같은 테스트에서 Spring Test Context의 DI는 동작합니다. ValueSource 역시 AutoSource와 마찬가지로 같은 추상화 개체를 구현하고 있구요. 제가 AutoParams에서 특정 인자를 null로 설정해야 할거라고 말씀드린 이유는, Spring Bean의 주입을 위해서였습니다. 
```java
@SpringJUnitConfig(TestConfig.class)
class DemoApplicationTests {

    @ParameterizedTest
    @ValueSource(strings = { "Dilbert", "Wally" })
    void people(String name, @Autowired List<Person> people, @Autowired OrderService orderService) {
        assertThat(people.stream().map(Person::getName).filter(name::equals)).hasSize(1);
        assertThat(orderService).isNotNull();
    }

    @Configuration
    static class TestConfig {

        @Bean
        Person dilbert() {
            return new Person("Dilbert");
        }

        @Bean
        Person wally() {
            return new Person("Wally");
        }

        @Bean
        OrderService orderService() {
            return new OrderServiceImpl();
        }
    }

    static class OrderServiceImpl implements OrderService {}

    static class Person {
        private String name;

        public Person(String name) {
            this.name = name;
        }

        public String getName() {
            return name;
        }
    }
}
```

**Comment by gyuwon** [comment]
@Rebwon 예시로 들어주신 코드에서 `@ValueSource`는 두번째, 세번째 매개변수 인자로 `null`을 담은 요소가 3개인 `Arguments`가 아니라 요소가 하나인 `Arguments`를 생성할 거에요.

**Comment by Rebwon** [comment]
@gyuwon null을 return하는건 코드를 꼼꼼히 보지 못했던 잘못된 결정이었습니다. 질문에 대한 꼼꼼한 답변 감사합니다 :)

**Comment by mhyeon-lee** [comment]
@gyuwon @Rebwon
아직 자세히 보지는 못했습니다만, `ArgumentsProvider` 가 ParameterResolver 를 구현하고 `@Autowired` 등은 support 하지 않도록 제외해야 될거 같습니다.
지금 구현하고 있는 `ArgumentsProvider` 인터페이스 와의 호환 등을 봐야 될거 같으니 제가 시간이 될때 보고 수정하도록 하겠습니다.

#101 이슈와 중복이기 때문에 이 이슈는 닫고 #101 에서 진행하도록 하겠습니다.
