### ISSUE TITLE
String 생성 범위 지원

### ISSUE THREAD

**Issue by wicksome** [JavaUnit/AutoParams#111]
```java
@ParameterizedTest
@AutoSource
void testStringMaxScope(@Scope(max = 10) String str) {
}

@ParameterizedTest
@AutoSource
void testStringMinScope(@Scope(min = 10) String str) {
}

@ParameterizedTest
@AutoSource
void testStringFixedLength(@Scope(length = 10) String str) {
}
```

위와 같이 생성되는 인자의 범위를 지정할 수 있으면 좋을 것 같아 이슈 생성합니다.

---

이슈를 만들고 생각해보니... 파라미터에 제약조건이 있다면 `ParameterizedTest`가 아닌 `Test`로 검증해야될 것 같기도 하네요

**Comment by jwChung** [comment]
의견 감사합니다. 라벨 규칙 #24 에 따라 구현 확정되기 전에는 question 라벨 달아 두겠습니다.

**Comment by gyuwon** [comment]
@wicksome `@Scope` 애노테이션은 존재하는 것인가요, 아니면 새롭게 제안하시는 건가요?

**Comment by wicksome** [comment]
> @wicksome `@Scope` 애노테이션은 존재하는 것인가요, 아니면 새롭게 제안하시는 건가요?

@gyuwon 예시로 작성한 코드입니다.

**Comment by gyuwon** [comment]
@wicksome 애노테이션 매개변수는 문자열의 길이를 뜻하는 것으로 보이는데 그렇다면 `@Length` 또는 `@StringLength`가 명확하지 않을까요? 그리고 혹시 JSR-380의 `@Size`를 사용하는 것은 어떨까요?
https://beanvalidation.org/2.0/spec/#builtinconstraints-size

**Comment by mhyeon-lee** [comment]
JSR-380 을 사용하기로 아래에서 논의되었으므로 우선 @Size 로 가면 되겠네요
https://github.com/JavaUnit/AutoParams/issues/4#issuecomment-799293685

#4 와 중복 이슈로 보입니다.

**Comment by wicksome** [comment]
JSR-380 사용이 괜찮을 것 같습니다.

추가로, 길이 제한뿐만 아니라 생성되는 문자열의 범위를 지정하는 건 어떤가요?
예를 들어.. `a-zA-Z`, alphanumeric, `+=-/*` 와 같이 큰 카테고리입니다.
생성 제한이 더 디테일하게 생기면 `ParameterizedTest`가 아니라 하나씩 나누는게 더 나을 것 같아서요..
이부분은 다른분들의 의견 궁금합니다.

**Comment by mhyeon-lee** [comment]
@wicksome 의견 감사합니다. 아마도 Customization API 설계에서 디자인이 어느정도 정해지면 각 속성 종류에 대한 고도화된 customization 기능 제공이 검토될 수 있을거 같군요

**Comment by gyuwon** [comment]
JSR-380 지원으로 의견이 모아진 것으로 판단해 닫겠습니다. JSR-380의 구체적 지원은 세부 내용 별 추가 이슈를 등록해 주세요.
