### ISSUE TITLE
Custom Generator 지원

### ISSUE THREAD

**Issue by kingbbode** [JavaUnit/AutoParams#13]
비지니스에서 필요한 특수한 값의 형식과 범위를 일반적인 옵션의 제공으로 커버하기에는 무리가 있을 것으로 생각됩니다.
사용자에게 `ObjectGenerator` 를 구현할 수 있도록 제공한다면 좋지 않을까 생각합니다.

**Comment by gyuwon** [comment]
말씀하신 필요성에 대해서는 전적으로 공감합니다. 그리고 이 프로젝트에게 영감을 준 AutoFixture는 아주 풍부한 커스터마이징 API를 제공하고 저는 이 API들을 적극 사용합니다.

하지만 API 공개는 매우 조심스러운 일 입니다. 이미 AutoParams를 현장에서 사용하고 있다는 분둘이 계시고 저도 회사 프로젝트에 사용하기 시작했습니다. 비록 현재 버전이 `0.0.*`라 할지라도 사용자가 있는 상황에서 가급적 API breaking change는 없어야 합니다.

저는 AutoParams 프로젝트를 시작할 때부터 커스터마이징을 API를 염두하고 있었습니다. 말씀처럼 이것 없이는 사용성이 충분히 확보되지 못합니다. 하지만 저는 아직 Java와 JUnit에 적합한 API 설계에 대한 확신이 없습니다. 쉽게 결정된 공개 API는 breaking change를 야기할 가능성을 높이고 결국 사용자들은 AutoParams 버전을 높이기 위해 그들의 많은 코드를 수정해야 합니다. 이런 문제들을 고민하기 위해 #3 이슈를 준비하고 있습니다.

다시 말씀드리지만 공개 API 설계 확장은 매우 조심스럽고 방어적이어야 합니다. 커스터마이징 API에 대한 의견이 있으면 #3 이슈에 공유 부탁드립니다.

**Comment by kingbbode** [comment]
충분히 이해하였습니다. #3 를 살펴보겠습니다. :)

**Comment by gyuwon** [comment]
@kingbbode 이해해주셔서 고맙습니다! 👍
