### ISSUE TITLE
ObjectQuery 디자인 개선 - 매개변수 인자와 컬렉션 요소 외 어떤 쿼리가 더 필요한가

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#142]
> #141 이슈의 하위 이슈입니다.

다음의 경우 외에 어떤 개체생성 요구가 필요할까요?

- 매개변수 인자 생성
- 컬렉션(또는 스트림<strike>; 빌어먹을 Java에서는 왜 컬렉션이 스트림이 아닌 건가 🤦‍♂️</strike>) 요소 생성

현재 설계는 두 경우 모두 `ObjectQuery` 클래스와 하위 클래스인 `GenericObjectQuery` 클래스가 지원합니다.

---

- 키-값 쌍

**Comment by mhyeon-lee** [comment]
key / value 로 구분되는, `Map<?, ?>` `Entry<?, ?>` 도 별도의 요구가 필요할 수 있겠습니다.

**Comment by gyuwon** [comment]
그러네요. 현재도 그 케이스가 있군요.

**Comment by jwChung** [comment]
`Type` 의 하위타입이 많군요.

<img src="https://user-images.githubusercontent.com/3784448/112788335-a3595680-9095-11eb-8f4d-3f8cbd3daa36.png" width="500" />

쿼리가 `Type`의 상위 타입을 표현한다면 `WildcardType` 정보도 활용할 수 있긴하겠네요.

쿼리에 `Type` 이외의 정보가 필요하진 않은지를 생각해보면 우선 #111 같은 시나리오를 지원하기 위해 Annotation 정보가 필요하겠습니다.

**Comment by gyuwon** [comment]
타입 정보를 갖지 않는 쿼리가 있을 수 있을까요?

**Comment by jwChung** [comment]
타입 정보를 갖지 않는 쿼리 시나리오는 생각나지 않네요.

--------------------------------------------------

`Map<String, List<Integer>>` 중첩 gengeric 이 생각나는군요.

**Comment by gyuwon** [comment]
그럼 `ObjectQuery` 클래스는, 정적 멤버 빼고, 현재 디자인을 유지해도 될까요?

**Comment by jwChung** [comment]
@gyuwon `GenericObjectQuery` 없이 `ObjectQuery` 클래스의 타입을 `Type`으로 표현하는 방법도 있을 것 같은데  #143에서 논의를 해볼까요?

**Comment by gyuwon** [comment]
매개변수 외 쿼리 요구 의견이 나오지 않아 이슈를 닫겠습니다.
