### ISSUE TITLE
ObjectQuery 디자인 개선 - 매개변수 인자와 컬렉션 요소의 개별 특징은 어떻게 표현할 것인가

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#143]
> #141 이슈의 하위 이슈입니다.

개체생성 요청 시 매개변수 인자와 컬렉션 요소의 어떤 특징들이 포함되어야 할까요? 현재는 인자와 요소의 공통 특징인 타입만 표현됩니다. 하지만 예를 들어, #15 처럼 인자를 생성할 때에 매개변수를 수식하는 애노테이션이 필요할 수 있습니다.

### 매개변수 인자 요청 정보
- 타입
- 이름
- 애노테이션 목록

### 컬렉션 요소 요청 정보
- 타입

**Comment by jwChung** [comment]
매개변수 위치 인덱스 정보는 필요할까요? name과 같이 메타 정보로 사용될 수 있을 것 같은데 중요도는 name 보다 떨어지는 것 같네요.

---------------------------------

### 방법1
타입 정보가 가장 중요할 것 같은데,  현재는 `Type` 하위타입 둘을 아래와 같은 쿼리 두개로 대응해서 사용하고 있습니다. 이 방법으로 `WildcardType` 을 지원한다면  쿼리 타입이 하나 더 필요할지도 모르겠습니다.

- `Calss<T>` => `ObjectQuery` 
- `ParameterizedType` => GenericObjectQuery 

### 방법2
`ObjectQuery` 가 가지는 타입정보를 `Calss<T>`대신 상위 타입인 `Type` 을 사용하는 방법도 대안이 될 수 있을 것 같습니다. 이때는 `ParameterizedType` 정보를 가지는 `GenericObjectQuery` 쿼리 타입이 없어도 될 것 같네요.

### 방법3
`Object` 같은 쿼리 타입으로 받아서, 다양한 타입 방식을 인정해버리는 것입니다.(AutoFixture 방식) 다음과 같은 값을 쿼리 타입으로 사용할 수 있을 것 같습니다.

- `java.lang.reflect.Parameter`
- `Class<T>`
- `Constructor<T>`

**Comment by gyuwon** [comment]
저는 AutoFixture를 사용하면서 3번 방식이 썩 맘에 들지 않았습니다. 최상위 쿼리 타입이 있다면 하위 타입을 찾아서 내가 뭘 사용할 수 있을 지 파악할 수 있겠지만 `Object`로 주어지면 뭘 해야 할 지 난감하거든요.

**Comment by gyuwon** [comment]
@jwChung @mhyeon-lee 방법2로 PR을 만들어볼게요. 거기서 논의해봐요.
