### ISSUE TITLE
Builder 를 Mutable / Immutable 로 설계할지 논의합니다.

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#146]
아래 PR 리뷰에서 나왔던 Mutable / Immutable 에 대해서 논의합니다.

https://github.com/JavaUnit/AutoParams/pull/99#discussion_r599475866

1. 사용자 사용성에 Mutable / Immutable 중 어느것이 기대되거나 편리할 것인가?
2. Mutable 하다면 fix 의 반환형이 void 일 것인가? Fluent 를 위해 this 를 반환해도 괜찮을까?
3. Builder 와 ImmutableBuilder 로 분리해서 제공하는건 어떤가?

**Comment by gyuwon** [comment]
저는 빌더 패턴이 fluent API를 제공할 때 불변하게 처리되는 경우는 본적이 없고 불변했을 때 장점이 그리 느껴지지 않습니다.

**Comment by mhyeon-lee** [comment]
저도 아래 적은것 처럼 빌더 패턴은 mutable 이 기대될거 같습니다.
https://github.com/JavaUnit/AutoParams/pull/99#discussion_r602968969

@jwChung 님의 의견을 듣고 결정하겠습니다.

**Comment by jwChung** [comment]
네 `this`반환 fluent API로 가시죠.
