### ISSUE TITLE
Builder의 제네릭 적용

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#158]
@mhyeon-lee 님이 작성해주신 `fix` 메서드까지 보고 나니 `Builder` 클래스에 제네릭이 적용되기 보다는 `build` 메서드에 제네릭이 적용되는 것이 더 유용하지 않을까 싶습니다. 어떻게 생각하시나요?

**Comment by gyuwon** [comment]
@mhyeon-lee @jwChung 의견 부탁드립니다.

**Comment by mhyeon-lee** [comment]
그러면 `build` 호출시 class 를 넘기게 되는걸까요?

```java
void test(Builder builder) {
        int actual1 = builder.fix(int.class, 1).build(int.class);
        ComplexObject actual2 = builder.build(ComplexObject.class);
}

```

**Comment by jwChung** [comment]
`fix` 외에 constructor 선택 기능이나 다른 기능에선 `Builder.build(Class)` servie locator 방식보다 `Builder<T>.build()` 팩토리 방식이 좋을 수 있을 것 같아요. `fix` 외 우리가 지원해야하는 기능을 먼저 고민하면 어떨까요?

**Comment by gyuwon** [comment]
@jwChung 왜 좋다고 생각하시는지 궁금합니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 그렇게 되겠죠. 같은 기준을 갖는 두 형식의 개체가 필요할 때 빌더 2개를 만들어 `fix` 등 커스터마이징을 두 번해야 한다면 많이 불편할 것 같아요.

**Comment by jwChung** [comment]
@gyuwon 생성자 선택기능을 추가한다면 다음과 같이 타입이 먼저 지정되어야 하지 않을까해서요
```java
Builder<T>.constructor(ctors -> ctors.first()).build();
```

**Comment by gyuwon** [comment]
@jwChung 이렇게 하면 많이 불편할지와 생성사 선택의 불편함의 빈도, 제가 위에서 언급한 둘 이상의 타입에 대해 빌더를 동일하게 여러번 세팅하는 불편함의 빈도도 생각해 봐야겠어요.

```java
builder.constructor(T.class, ctors -> ctors.first()).build();
```

**Comment by jwChung** [comment]
fixture 로 한번 받아서 여러타입 빌드에 쓰면,

```java
fixture.builder(Foo.class).fix(Int.class, 10).build()
```
이렇게 되네요. 익숙한 표현이군요.

**Comment by mhyeon-lee** [comment]
@gyuwon @jwChung 
의견 주신 것처럼 서로 다른 타입이지만 비슷한 형식의 개체가 필요할때는 셋팅의 수고가 줄어들 수도 있지만, 반대로 전혀 다른 타입의 개체 생성 정의시 서로 정의가 의도하지 않게 섞일 수도 있겠다는 생각도 듭니다. Builder 를 각각 정의해서 사용해도 되긴 하지만 Generics 가 있는게 속성을 정의하는 입장에서 대상이 명확할거 같다는 생각도 듭니다.

@gyuwon 님이 의견주신 것의 역할이 좀 더 큰 범위를 지원하게 되는거 같은데 Builder 가 아닌 다른 이름으로 별도로 만드는건 어떨까요?
공통으로 속성 정의 기반으로 `Builder<T>` 를 만들어 줄 수도 있을거 같고요

**Comment by gyuwon** [comment]
@jwChung 익숙하네요 ㅋㅋ

**Comment by mhyeon-lee** [comment]
@gyuwon @jwChung AutoFixture 에서 저렇게 제공되나요?

**Comment by gyuwon** [comment]
설계 변경의 확실한 이유가 도출되지 못한 것 같으니 이 이슈는 일단 닫겠습니다.

**Comment by jwChung** [comment]
@mhyeon-lee 옙 ㅋㅋ
