### ISSUE TITLE
@Customization 설계 변경 검토

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#175]
@jwChung @mhyeon-lee 매개변수를 가진 `Customizer` 구현체 생성자를 사용할 일은 없을까요?

```java
@ParameterizedTest
@AutoSource
@Customization(RangeCustomizer.class, arguments = {int.class, 0, 100})
@Customization(RangeCustomizer.class, arguments = {long.class, 1000, 10000})
```

**Comment by jwChung** [comment]
`arguments`가 `Object[]` 타입이 되나요?  `Object[]` 타입은 어노테이션 내에서 사용할 수가 없네요 ㅜㅜ

**Comment by mhyeon-lee** [comment]
네 기본 타입 밖에 안되서 arguments 는 String 으로만 표현될거 같습니다.
제 생각에 `@Customization` 으로 풍부한 옵션을 주기에는 한계가 있어서 `@CsvSource` 처럼 String 으로 parsing 할 수 있는 arguments 정도만 지원 가능할 수 있을거 같습니다.

좀 더 강력한 Customizer 는 Builder 에 주입시켜야 될거 같기도 하고요

**Comment by gyuwon** [comment]
슬픈 현실이군요. 이 이슈는 닫겠습니다. 😥
