### ISSUE TITLE
gradle 멀티 모듈 구성

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#19]
이후 kotlin 이나 특정 라이브러리 애노테이션 등을 서포트 하는 플러그인이 필요할 때 확장 모듈이 필요할 가능성이 높을거 같습니다. 
별도의 repo 를 파는 것도 방법이지만, 하나의 repo 에서 multi module 을 구성하는게 장점이 더 많다고 생각됩니다.

현시점에서 멀티 모듈을 논의하는 시점이 이를 수도 있지만, kotlin 모듈의 필요성은 곧 이슈화 될거 같다는 생각도 들어서 미리 멀티 모듈로 구성을 해놓는건 어떨지 제안해봅니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 필요할 것 같아요. 조만간 Mockito 지원을 위한 위성 패키지 AutoParams.Mockito 를 만들 계획이거든요. 구체적인 안을 제시해 주실 수 있을까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
#22 에 autoparams 모듈만 설정된 샘플 구조를 올렸습니다.
아래와 같은 구조로 생각하고 있습니다.

- JavaUnit-AutoParams
    - build.gradle
    - autoparams
        - bulid.gradle
    - autoparams-kotlin
        - build.gradle
    - autoparams-mockito
        - build.gradle

**Comment by gyuwon** [comment]
@mhyeon-lee 모듈 디렉터리는 `autoparams.kotlin`보다 `autoparams-kotlin`이 관습인가요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
모듈 패키지명은 `autoparams.kotlin`  artifactId 는 autoparams-kotlin 으로 하면 어떨까 합니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 저는 보편적인 관습을 따르는 편이라 그렇게 하는 것이 관습이면 이견 없습니다. :)

**Comment by mhyeon-lee** [comment]
@gyuwon 멀티 모듈 초기 구조는 셋팅됐으므로 이 이슈는 닫겠습니다.
