### ISSUE TITLE
JavaBeans 스펙 객체 생성 전략 옵션 지원

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#196]
- JavaBeans 스펙의 객체 생성을 지원합니다.
- Spec
    - No Args Constructor 로 객체를 생성한 후 setter 메소드로 값을 주입한다.
    - No Args Constructor 는 public 접근자이다.
    - setter 메소드명은 `set` 으로 시작한다.
    - 반환형은 `void` 이다.
    - 매개변수는 1개 또는 2개를 가진다.
        - Indexed property 인 경우 2개이며, 첫번째 매개변수는 int 형이다.
<img width="583" alt="스크린샷 2021-05-04 오전 1 55 43" src="https://user-images.githubusercontent.com/5206572/116907028-fec1ca00-ac7b-11eb-8801-412917de1d53.png">

```java
// sample
PropertyDescriptor[] descriptors = Introspector.getBeanInfo(JsonSerializeObject.class).getPropertyDescriptors();
for (PropertyDescriptor descriptor : descriptors) {
    if (descriptor instanceof IndexedPropertyDescriptor) {
        Method method = ((IndexedPropertyDescriptor)descriptor).getIndexedWriteMethod();
        // method Invoke (index, value)
    } else {
        Method method = descriptor.getWriteMethod();
        // method invoke (value)
    }
}
```

- IndexedWriteMethod 와 WriteMethod 둘다 존재할 때 어떤 메소드를 선택할 것인가?

**Comment by gyuwon** [comment]
인덱스를 가진 setter인 경우 AutoParams는 어떻게 대응해야 할까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
size (3) 를 정해서 index 0 ~ n-1 까지 돌면서 생성된 객체를 셋팅해줘야 하지 않을까 생각됩니다.
같은 property 에 대해 인덱스를 가진 setter 와 일반 setter 둘 다 있을때는 뭐를 선택할지 잘 모르겠습니다. (일반 setter 선택이 나을거 같습니다.)

그리고 인덱스 Setter 는 구현하지 않고 있다가 요구사항이 있으면 구현해도 괜찮지 않을까 생각되긴 합니다.
(어제 JavaBeans Specification 을 보다가 인덱스 Setter 가 있는지 처음 알았습니다.)

**Comment by gyuwon** [comment]
@mhyeon-lee @jwChung setter 지원을 기본 기능으로 해야 할까요? 아님 `Customizer`로 제공해도 될까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
저는 기본 기능으로 넣지 않아도 될거 같습니다.
JavaBeans 설정이 필요한 타입을 지정하면, 해당 타입은 JavaBeans 스펙으로 생성하는 Customizer 를 제공하면 좋겠다고 생각됩니다.

**Comment by mhyeon-lee** [comment]
현재 ComplexObjectGenerator 에서는 생성자 선택으로 객체를 생성하고 있습니다. 
(@ConstructorProperties 또는 매개변수가 가장 적은 생성자 선택)

저는 이 생성자 선택 객체 생성 방식과 JavaBeans 객체 생성 중 한가지가 선택되는 방식을 지원하는 것으로 생각했습니다. 
    - JavaBeans 스펙으로는 public No Args 생성자로만 객체 생성 하고 Setter 를 실행함
    - 이후에 또 다른 생성 전략이 추가될 수 있음

아래서 @gyuwon 님 의견을 보니 기존 방식으로 객체가 생성된 후 Setter 속성을 추가로 처리할 것인지 여부를 선택하게 하는 것도 방법 중 하나가 될 수도 있을거 같습니다. 
https://github.com/JavaUnit/AutoParams/issues/205#issuecomment-835348276

Setter 속성을 어떻게 다루면 좋을지 의견 부탁드립니다.

1. ComplextObjectGenerator 에서 생성자 선택 방식과 JavaBeans 생성 방식을 선택한다.
2. 생성자 선택으로 객체 생성한 후 생성된 객체에 Setter 실행 여부를 판단한다.

**Comment by gyuwon** [comment]
JavaBeans 명세를 준수하는 형식의 개체를 생성하는 것은 현재의 코드로도 충분할 것 같습니다. 매개변수가 없는 생성자를 가진다면 그 생성자를 선택할 테니까요.

그렇다면 setter 호출을 해주는 `Customizer`가 제공되면 JavaBeans 개체를 잘 생성하게 되는 것 아닌가 싶습니다.

**Comment by mhyeon-lee** [comment]
다음의 테스트를 만족합니다.

```java
public class HasSetter {
    private String prop;
    public String getProp() { return prop; }
    public void setProp(String prop) { this.prop = prop; }
}
```
```java
@ParameterizedTest
@AutoSource
@Customization(PropertyWriter.class)
public void sut_sets_property(HasSetter value) {
    assertNotNull(value.getProp());
}
```
