### ISSUE TITLE
checkstyle 및 formatter 설정

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#20]
- checkstyle 및 formatter 설정에 대해 논의합니다.
- 우선 checkstyle 및 formatter 가 필요할지에 대해 의견 부탁드립니다.
    - checkstyle 은 gradle 로 검사할 수 있지만, checkstyle 에 맞는 formatter 를 셋팅하는건 간단하지만은 않습니다.
    - 보통 Intellij formatter 로 맞추지만 vs code 등 다른 툴을 호환하려면 각 툴에 맞는 formatter 가 각각 정의되어야 합니다.

**Comment by gyuwon** [comment]
전 완전 찬성입니다!

**Comment by mhyeon-lee** [comment]
@gyuwon 주로 사용하시는 툴이 어떻게 되시나요? VSCode 인가요?

**Comment by gyuwon** [comment]
@mhyeon-lee 아무거나 상관 없어요. VS Code도 불편하고 IntelliJ도 불편하고 🤣
IntelliJ만 고려하고 초기화 한 후 다른 도구에도 사용할 수 있도록 formatter를 늘려가는 건 어떤가요?

**Comment by jaceshim** [comment]
가장 보편적인(?) Google Java  style guide 한표 쏩니다!

[](https://github.com/google/google-java-format)
[](https://google.github.io/styleguide/javaguide.html)

**Comment by gyuwon** [comment]
@jaceshim 저는 잘 몰라서 @mhyeon-lee @jwChung 님 및 다른 분들 의견 부탁드립니다.

**Comment by mhyeon-lee** [comment]
Google Java style guide 사용에 이견은 없지만, indentation 2 인 것을 4로 설정하고 싶긴 합니다.
https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation

**Comment by jwChung** [comment]
저도 최근에 설정한 값을 보니 4,8 들여쓰기로 수정해서 사용했네요.

https://github.com/jwChung/junit4-pioneer/blob/master/config/checkstyle/checkstyle.xml#L19-L31

**Comment by gyuwon** [comment]
@jwChung `8` 꼭 해야 하나요?

**Comment by mhyeon-lee** [comment]
indentation 관련 아래 설정이 있군요
기존 2만 4로 변경할지, 기존 4도 8로 변경할지 결정해주세요  (저는 상관없습니다.)
```xml
        <module name="Indentation">
            <property name="basicOffset" value="2"/>
            <property name="braceAdjustment" value="2"/>
            <property name="caseIndent" value="2"/>
            <property name="throwsIndent" value="4"/>
            <property name="lineWrappingIndentation" value="4"/>
            <property name="arrayInitIndent" value="2"/>
        </module>
```

**Comment by jwChung** [comment]
@gyuwon 저는 그냥 곱하기 2했습..

junit 참고할려고 갔다가 탭으로 되어 있어서 도망 나왔습니다.

**Comment by gyuwon** [comment]
F**cking tabs!

**Comment by mhyeon-lee** [comment]
@jwChung 님 저희 맨날 탭 쓰고 있자나요

**Comment by gyuwon** [comment]
`8` 왜 하는지 모르는 건 아닌데 안끌려서 약하게 `4`만 쓰는 건 어떨지 의견 드려봅니다. `4`만 썼을 때 크게 불편했던 분들 계실까요?

**Comment by jwChung** [comment]
@mhyeon-lee 스프링 소스는 어때요?

**Comment by jwChung** [comment]
core  4, 8 쓰는군요. 개인적으론 어느 것이든 상관 없는데, 자바에서 많이 쓰는 스타일을 따르면 좋을 것 같습니다.

https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/AttributeAccessorSupport.java#L70-L71

**Comment by mhyeon-lee** [comment]
throwsIndent 가 4면 조금 불편해 보이기는 하군요

<img width="834" alt="스크린샷 2021-03-16 오후 10 28 26" src="https://user-images.githubusercontent.com/5206572/111316900-01a23480-86a7-11eb-8a56-ef921e3168d3.png">

<img width="853" alt="스크린샷 2021-03-16 오후 10 28 50" src="https://user-images.githubusercontent.com/5206572/111316928-05ce5200-86a7-11eb-9c3a-f3f9bdb498b8.png">

**Comment by mhyeon-lee** [comment]
인텔리제이 기본 설정은 space 에 thrrows indent 도 4인거 같습니다.

<img width="888" alt="스크린샷 2021-03-16 오후 10 32 58" src="https://user-images.githubusercontent.com/5206572/111317566-9e64d200-86a7-11eb-9c50-46cc57238d06.png">

**Comment by jaceshim** [comment]
저도 indentation 4 파입니다!

**Comment by gyuwon** [comment]
@mhyeon-lee 네. 저게 C#에선 문제되지 않는 것이 괄호 관습 때문이죠.

```cs
public void Print(
    int arg1,
    string arg2)
{ // <--
    Console.WriteLine(arg1);
    Console.WriteLine(arg2);
}
```

**Comment by mhyeon-lee** [comment]
allowMultipleEmptyLines -> false
allowMultipleEmptyLinesInsideClassMembers -> false

https://github.com/JavaUnit/AutoParams/pull/41#discussion_r595276141

**Comment by mhyeon-lee** [comment]
추가 rule 이 필요하면 이 이슈를 다시 열어주셔도 됩니다.
