### ISSUE TITLE
org.apache.commons:commons-math3:3.6.1 필요한가요?

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#203]
현재 `org.apache.commons:commons-math3:3.6.1` 의존성이 있는데 gradle 초기화할 때 들어간 것을 제가 확인하지 않은 듯 합니다. 이 의존성이 필요할까요?

**Comment by mhyeon-lee** [comment]
없어도 빌드되고 통과하는군요? 

저 라이브러리에 어떤 기능이 있는지는 잘 모르는데 제거하는게 좋을거 같다고 생각됩니다.
