### ISSUE TITLE
ComplextObjectGenerator customize 방법 지원 필요

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#205]
- 특정 타입에 대한 Customize 를 끼워넣기 위해서는 Customizer 구현체에서 원하는 타입은 Customize 된 Generator 로 생성하도록 제어할 수 있습니다.
- 그런데 ComplexObjectGenerator 의 generate 방식을 변경(Customize)하기 위한 방법이 없어 보입니다.
- ComplexObjectGenerator 의 내부 객체 생성 방식을 Customize 할 수 있는 기능 제공이 필요할거 같습니다.

좋은 방법이 있을까요?

**Comment by gyuwon** [comment]
제가내용을 잘 이해하지 못했습니다. 어떤 부분이 불가능할까요?

**Comment by gyuwon** [comment]
@mhyeon-lee #196 때문에 시작된 이슈군요. Setter 지원만 하면 된다고 생각했는데 블랙리스트를 가져야 할 이유가 뭘지 잘 모르겠습니다. Setter 지원을 위한 테스트 케이스를 작성한다면 이럴 거라고 생각했습니다.

```java
public class HasSetter {
    private String prop;
    public String getProp() { return prop; }
    public void setProp(String prop) { this.prop = prop; }
}
```

```java
@ParameterizedTest
@AutoSource
@Customization(PropertyWriter.class)
public void sut_sets_property(HasSetter value) {
    assertNotNull(value.getProp());
}
```

만약 이런 테스트를 만족시켜야 할 경우 현재 API에서 부족한 것이 무엇일까요?

**Comment by mhyeon-lee** [comment]
@gyuwon
> Setter 지원만 하면 된다고 생각했는데

현재 ComplexObjectGenerator 의 생성자 선택 객체 생성과 JavaBeans 생성 방식 중 한가지가 선택되게 하는 방식을 생각하고 있는데요.
기존 생성 방식에 Setter 가 있다면 추가로 Setter 를 실행하게 하는 방식을 생각하신 걸까요?

**Comment by mhyeon-lee** [comment]
예시로 주신 `PropertyWriter` Customizer 를 구현하는 방법이 여러가지가 있을 수 있겠는데요

Customizer 구현시 넘어온 ObjectGenerator (CompositeObjectGenerator) 에서 어떻게  Setter 를 지원하는 동작을 끼워 넣을지 조언이 필요합니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 저는 아직 구현이 아니라 요구사항을 고민해야 한다고 생각돼요. 우리가 만족시키려는 시나리오가 뭔지 명확해지고 나서 구현을 고민해야 할 것 같습니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 

> Customizer 구현시 넘어온 ObjectGenerator (CompositeObjectGenerator) 에서 어떻게 Setter 를 지원하는 동작을 끼워 넣을지

이것 역시 구현에 대한 고민 같은데요, 우리는 개체가 어떤 생성기를 통해서 만들어졌는지 보다 만들어진 개체의 쓰기 속성을 어떻게 다뤄야 하는지가 중요할 듯 합니다.

**Comment by mhyeon-lee** [comment]
@gyuwon 
아직 요구사항 정의가 덜 된거로 보이는군요 
이 이슈는 닫고 #196 에서 요구사항을 정리하도록 하겠습니다.
