### ISSUE TITLE
위성 패키지의 본 패키지(autoparams) 의존성 관리

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#213]
`autoparams-mockito` 패키지 프로젝트를 추가하며 이 위성 패키지는 `autoparams` 패키지에 비해 변경이 현저히 적을 것으로 예상되어 두 패키지의 버전을 일치시키지 않도록 결정했다.

현재 `autoparams-mockito` 패키지는 `autoparams` `0.2.0` 이상 버전에서 동작하고 `autoparams` 참조는 `api 'io.github.javaunit:autoparams:0.2.0'`로 되있다.

앞으로 `autoparams` 패키지 버전이 올라가도 클라이언트 프로젝트가 `autoparams-mockito`를 사용하며 바이너리 버전 불일치를 겪지 않게 하려면 참조 방식을 어떻게 바꿔야 하나?

|autoparams|autoparams-mockito|autoparams 패키지 참조|
|--|--|--|
|0.2.0|0.0.1|`api 'io.github.javaunit:autoparams:0.2.0'`|
|0.2.1|0.0.1|`?`|

**Comment by gyuwon** [comment]
@mhyeon-lee @jwChung 이슈 등록했습니다.

**Comment by mhyeon-lee** [comment]
혼란이 적으려면, 사용자가 선택한 autoparams 의 버전과 autoparams-mockito 가 사용하는  autoparams 는 Runtime 에 같은 바이너리를 사용해야 될거 같습니다.

그래서 autoparams-mockito 에서 autoparams dependency 는 compileOnly 로 하고, 사용자가 dependency 로 지정한 autoparams 버전 바이너리를 Runtime 에 사용하도록 하는게 어떨까 생각됩니다.

---

그리고 배포된 버전을 명시하지 말고 현재 프로젝트의 모듈 바이너리를 의존하면 어떨까 싶습니다.

```
dependencies {

    compileOnly project(":autoparams")

    testImplementation project(":autoparams")

}
```

**Comment by gyuwon** [comment]
`autoparams-mockito`가 `autoparams`를 사용하고 둘은 별도의 패키지인데 왜 `api`가 아니고 `compileOnly`를 사용해야 하나요? 그렇게 되면 `autoparams-mockito`만 설치하면 동작하고 반드시 `autoparams`와 함께 설치해야 할 것 같은데 그게 Java 생태계의 관습인가요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
네 말씀하신대로 autoparams 를 함께 설치해야 됩니다.
보통은 버전을 맞추기 때문에 api 로 해서 `autopararms-mockito` 만 설치하도록 하는데 이렇게 버전이 다를 경우 보통 어떻게 하는지 잘 모르겠네요

dependency scope 에 따라 런타임 바이너리가 어떻게 참조되는지는 다시 테스트를 해봐야겠네요

**Comment by gyuwon** [comment]
그거 테스트 하다가 찾은 문제가 #214 이거에요 ㅎㅎ

**Comment by gyuwon** [comment]
저는 `autoparams-mockito` 버전이 `0.0.*` 이니 `api 'io.github.javaunit:autoparams:[0.2.0, )' 같은 것으로 테스트를 해보는 것도 괜찮지 않을까 싶습니다.
