### ISSUE TITLE
autoparams 패키지 메타데이터 누락

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#214]
현재 `io.github.javaunit:autoparams:0.2.0` 패키지를 설치한 후 다음 코드를 실행하면 모두 `null`이 반환된다.

```java
AutoSource.class.getPackage().getSpecificationTitle();
AutoSource.class.getPackage().getSpecificationVendor();
AutoSource.class.getPackage().getSpecificationVersion();
AutoSource.class.getPackage().getImplementationTitle();
AutoSource.class.getPackage().getImplementationVendor();
AutoSource.class.getPackage().getImplementationVersion();
```

이 정보들이 채워져야 한다.

**Comment by gyuwon** [comment]
@mhyeon-lee 혹시 이 문제 어디를 손봐야 하는지 아시나요? @jwChung

**Comment by mhyeon-lee** [comment]
@gyuwon 
META-INF 와 관련될거 같은데, 저녁에 한번 찾아보겠습니다.

**Comment by mhyeon-lee** [comment]
#216 에 올렸습니다.
참조하는 클래스가 포함된 Jar 의 `META-INF/MANIFEST.MF` 를 읽어서 저 메타 정보들을 반환합니다.

Jar 에서 읽기 때문에 자기 자신의 테스트에서는 저게 안 읽히네요 (이 부분은 따로 확인해봐야될거 같습니다.)

**Comment by gyuwon** [comment]
@mhyeon-lee 이거 지금 해결되었거나 문제 발생하는 곳이 없는 듯해서 닫겠습니다.
