### ISSUE TITLE
IntegerGenerator 버그

### ISSUE THREAD

**Issue by jinhwan2** [JavaUnit/AutoParams#220]
## 이슈
commit ```6687d9ab61cb00fed8557aba0fbb06f9cc9fc9b6```

IntegerGenerator.java

```java
return (int) Math.min(Integer.MAX_VALUE, annotation.value() + 1);
```

## 증상

```java
@ParameterizedTest
@AutoSource(repeat = 100)
void sut_accepts_max_constraint_for_int(@Max(Long.MAX_VALUE) int value) {
    assertThat(value).isLessThanOrEqualTo(100);
}
```

<img width="825" alt="스크린샷 2021-05-11 오후 12 33 41" src="https://user-images.githubusercontent.com/21194094/117754354-20f7b100-b255-11eb-9fe3-ce3fa31d186e.png">

bound
```
expected Long.MAX_VALUE
actual   0
```

## 원인
Overflow

```
Long.MAX_VALUE + 1; // -9223372036854775808
(int)Long.MAX_VALUE + 1; // 0
```

**Comment by nallwhy** [comment]
`Math.addExact/2` 를 이용한 `AddWihtoutOverflow/2` 같은 유틸성 함수를 만들어서 저런 부분마다 쓰는 식으로 해결해야 할까나요.

**Comment by JuJinPark** [comment]
아래와 같은 상황에서는 테스트는 모두 통과하지만 origin 값 즉 랜덤으로 int를 생성할시 최소 값은 항상 -1이 되는데 이는 문제가 없는 상황일까요?
```
    @ParameterizedTest
    @AutoSource(repeat = 100)
    void sut_accepts_min_constraint_for_int(@Min(Long.MAX_VALUE) int value) {
        assertThat(value).isGreaterThanOrEqualTo(100);
    }
```
부족하지만 나름 해결 방안을 두가지를 생각해 봤는데 사용자 측면에서는 어떤 방법이 더 나을 까요? 🤔 
- IntegerGenerator에서 annotation.value()값의 범위를 체크해서 Integer range을 넘어가면 exception을 던지다.
- IntegerGenerator에서 annotation.value()값이 Int 숫자 range을 넘어가면 특정 값으로 임의로 변경한다 (Long.MAX_VALUE -> Integer.MAX_VALUE, Long.MIN_VALUE -> Integer.MIN_VALUE).

**Comment by gyuwon** [comment]
예외 발생은 사용하는 입장에서 자연스럽지 않다고 생각합니다.

**Comment by JuJinPark** [comment]
@gyuwon 저는 int 값을 랜덤으로 생성시에 int 값의 범위를 넘어서는 요청이 들어오면 잘못된 요청이라 간주하여 예외를 발생시키는것도방법이라고 생각했는데 ...
혹시 어떤 면에서 자연스럽지 않은지 알수 있을까요? 😄

**Comment by gyuwon** [comment]
@JuJinPark 제가 잘못봤네요. `Integer.MAX_VALUE` 보다 큰 설정에 대해서는 예외가 발생해도 괜찮을 것 같아요.
