### ISSUE TITLE
Builder 패턴 지원

### ISSUE THREAD

**Issue by suhyeon** [JavaUnit/AutoParams#224]
`// Example`
`Purchase entity = Purchase.builder.build();`

와 유사하게 builder 패턴을 사용해서 개체를 생성하도록 정의된 경우도 지원하도록 한다.

**Comment by mhyeon-lee** [comment]
@suhyeon 
아래 이슈의 `3. @Builder 스펙` 에 해당하는 내용이 맞을까요?
https://github.com/JavaUnit/AutoParams/issues/66

**Comment by suhyeon** [comment]
@mhyeon-lee 네! 맞습니다! 기존에 이슈가 있었던걸 확인하지 못했네요.. 이 이슈는 닫겠습니다!
