### ISSUE TITLE
MockitoCustomizer 에서 Object 타입도 mock 처리

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#227]
현재 Object 타입은 `ComplexObjectGenerator` 에서 `new Object()` 로 생성하고 있습니다.
`new Object()` 가 크게 의미가 없어서 MockitoCustomizer 에서 mock 으로 처리해주면 어떨까요?

**Comment by gyuwon** [comment]
그렇게 하면 어떤 효과가 있을까요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
이슈를 잘못 생각하고 올린거 같습니다. 별로 할 수 있는게 없네요
이 이슈는 닫겠습니다.
