### ISSUE TITLE
@AutoParameterizedTest 어노테이션

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#23]
`@ParameterizedTest` 대신 `@AutoParameterizedTest` 어노테이션을 만들어 junit에서 제공하는 data source 기능은 그대로 사용하는 것은 어떨까요? 지정하지 않는 파라메타 값에 대해서만 익명(anonymous) 값을 넘겨 주는 것으로요.

`AutoArgumentsProvider`를 source 타입 별로 지정하면,   customizatoin(#3) 할 때 새 `AutoArgumentsProvider` 이 만들어질테고 이것을 사용하기 위해 data soucrce를 타입별로 새로 정의해야하는 번거로움을 해결할 수 있을 것 같습니다.

**Comment by gyuwon** [comment]
@jwChung 괜찮을 것 같긴 한데 말씀하신 번거로움이 어떤건지 잘 이해하지 못했습니다. 예시 코드롤 설명해 주실 수 있을까요?

**Comment by gyuwon** [comment]
@jwChung 코드를 좀 봤는데 쉽지는 않겠어요.

```java
@Target({ ElementType.ANNOTATION_TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@Documented
@API(status = EXPERIMENTAL, since = "5.0")
@TestTemplate
@ExtendWith(ParameterizedTestExtension.class)
public @interface ParameterizedTest {
}
```

위 코드 중 핵심적인 역할을 하는 `ParameterizedTestExtension` 클래스가 공용 API가 아닙니다. JUnit API가 `@ParameterizedTest`를 직접 확장하길 원하지 않는 것 같아요.

**Comment by jwChung** [comment]
@gyuwon 아직 코드를 자세히 보지 못했는데 확장포인트가 없으면 불가능하겠네요 ㅜㅜ 저도 살펴볼께요.

**Comment by gyuwon** [comment]
@jwChung 아 이해했습니다. 바로 AutoFixture가 가진 번거로움이군요! 🤣

**Comment by jwChung** [comment]
@gyuwon 아 ㅜㅜ 꽁꽁 닫아 놨군요. 공용 API가 아닌 녀석을 죄다 만드는 건 좋지 않아 보이네요.

**Comment by gyuwon** [comment]
@jwChung Exactly

**Comment by jwChung** [comment]
더 논의할 필요 없을 것 같네요. 이슈 닫겠습니다.
