### ISSUE TITLE
IntegerGenerator max 값 미포함 bug

### ISSUE THREAD

**Issue by JuJinPark** [JavaUnit/AutoParams#231]
## 이슈
IntegerGenerator max 값이 Integer.MAX_VALUE 보다 크거나 같을 시 max 값은 랜덤 integer 생성범위에서 제외된다.

## 이유
현재 랜덤 int를 생성하는 ThreadLocalRandom.nextInt API와 설명에 따르면 bound값은 범위에서 제외된다.

ThreadLocalRandom.java
> Returns a pseudorandom int value between the specified origin (inclusive) and the specified bound (exclusive).
```
    public int nextInt(int origin, int bound) {
        if (origin >= bound)
            throw new IllegalArgumentException(BAD_RANGE);
        return internalNextInt(origin, bound);
    }
```

현재 IntegerGenerator 구현상 bound 값은 최대 Integer.MAX_VALUE 임으로 max 값이 Integer.MAX_VALUE 보다 더 크거나 같을 시 max 값은 랜덤 integer 생성범위에서 제외된다.

IntegerGenerator.java
```
    private int getBound(ObjectQuery query) {
        if (query instanceof ArgumentQuery) {
            ArgumentQuery argumentQuery = (ArgumentQuery) query;
            Max annotation = argumentQuery.getParameter().getAnnotation(Max.class);
            if (annotation != null) {
                long value = Math.max(Integer.MIN_VALUE, annotation.value());
                if (value < Long.MAX_VALUE) {
                    value = value + 1;
                }
                return (int) Math.min(Integer.MAX_VALUE, value);
            }
        }

        return Integer.MAX_VALUE;
    }
```

## 테스트 케이스
```
    @ParameterizedTest
    @AutoSource(repeat = 100)
    void sut_exclude_max_value_when_gte_than_integer_max_value(@Min(Integer.MAX_VALUE-1) @Max(Long.MAX_VALUE) int value) {
        assertThat(value).isEqualTo(Integer.MAX_VALUE-1);
    }

```
위에 테스트가 항상 통과하여 Integer.MAX_VALUE가 제외된다는걸 확인 할 수 있다.

**Comment by JuJinPark** [comment]
ThreadLocalRandom 사용법을 이렇게 바꿔보는 건 어떨까요?
```
ThreadLocalRandom.current().nextInt((bound-origin)+1)+origin
```

**Comment by JuJinPark** [comment]
자신보다 큰 숫자 타입으로 랜덤 숫자를 생성하는 방향은 어떨까요? 🤔 
```
int value = (int)ThreadLocalRandom.current().nextLong((long)origin, (long)bound +1);
```

**Comment by gyuwon** [comment]
@JuJinPark 테스트만 통과하면 상관 없지 않을까요? :)

**Comment by JuJinPark** [comment]
@gyuwon 사실 변별력 있는 테스트를 어떻게 작성해야 할지 몰라 pr를 요청 못했습니다. 😢 
혹시 어떻게 테스트 케이스를 작성하면 max도 range에 포함되는지 검증 할 수 있을까요? 🙇

**Comment by gyuwon** [comment]
@JuJinPark 지금 다른 이슈에 집중하고 있어서 이게 마무리 되면 저도 한 번 살펴보겠습니다.

**Comment by gyuwon** [comment]
@JuJinPark PR(#252) 작성했습니다 :)

**Comment by JuJinPark** [comment]
@gyuwon 저렇게도 해결할 수 있겠네요 👍  
참고해서 다른 이슈들도 해결하겠습니다. 😄
