### ISSUE TITLE
Support Kotlin

### ISSUE THREAD

**Issue by nallwhy** [JavaUnit/AutoParams#239]
이하 다 틀린 내용입니다

https://github.com/JavaUnit/AutoParams/issues/239#issuecomment-850991306 를 참고해주세요.

### 문제 상황

Kotlin class 는 Java bytecode 로 변환될 때 arguments 를 받지 않는 constructor 를 기본으로 만드는 것 같습니다.

현재 AutoParams 의 ComplexObjectGenerator 에서 사용할 constructor 를 찾는 우선순위는
- `@ConstructorProperties` 가 붙은 constructor
- arguments 수가 적은 constructor

이기 때문에 `@ConstructorProperties` 가 붙은 constructor 가 없다면 arguments 를 받지 않는 constructor 가 항상 먼저 선택되게 됩니다.

### 해결 방법

Kotlin 에서 만드는 constructor 중 default 로 사용되는 constructor 는 `kotlin.jvm.internal.DefaultConstructorMarker` 라는 인자를 마지막에 받도록 되어있는 것 같습니다.

참조: https://stackoverflow.com/a/53912965/2259817

이를 이용해서 autoparams-kotlin 모듈을 만들 수 있지 않을까 싶은 생각이 듭니다.

**Comment by gyuwon** [comment]
데이터 클래스가 아닌 경우에도 발생하는 문제일까요?

**Comment by nallwhy** [comment]
@gyuwon 추정을 해보고 작업을 하면 재밌을 것 같아서 추정을 먼저 해보고 확인해보겠습니다.

https://kotlinlang.org/docs/data-classes.html 에 따르면

```
The compiler automatically derives the following members from all properties declared in the primary constructor:

equals()/ hashCode() pair

toString() of the form "User(name=John, age=42)"

componentN() functions corresponding to the properties in their order of declaration.

copy() function (see below).
```

정도의 차이가 있는 것 같기 때문에, constructor 부분이 다를 이유는 없지 않을까? 라고 생각해봅니다.

**Comment by nallwhy** [comment]
일단 data class 라고 다르지 않다는 것은 확인했는데,
지금 Kotlin Supporting 이 되지 않던 것이 아니었습니다 하하하하하하
일반적으로 Kotlin 지원은 매우 잘 됩니다.
위에 틀린 내용들은 다 수정해놓도록 하겠습니다.

저번에 테스트 하면서 모든 필드가 null 로 initializing 되었던 원인은
`kotlin-jpa` 라는 plugin 이 `@Entity` 가 붙어있는 class 를 JPA 에서 사용할 수 있도록 하기 위해
자동으로 no argument constructor 를 생성하고 있기 때문이었습니다.

위에서 언급했던 `kotlin.jvm.internal.DefaultConstructorMarker` 의 경우 default value 들이 지정된 arguments 가 있는 constructor 의 경우에 무엇이 원래 있던 constructor 인가 표시하기 위한 용도인 것 같고

secondary constructors 가 추가되었을 때는 따로 붙지 않습니다.
(즉, `Class.getConstructor/1` 의 결과들만 보고는 무엇이 primary constructor 인지 알 수 없을 것 같습니다.)

example
```kotlin
// 직접 secondary constructor 를 추가한 경우
class Test1(
    val id: Long
) {
    constructor(): this(1)
}

// kotlin-jpa 에서 no arguments constructor 를 추가한 경우
@Entity
class Test2(
    val id: Long
)

constructors1 = {Constructor[2]@1888} 
 0 = {Constructor@2149} "public com.healingpaper.payment.domain.payments.Test1(long)"
 1 = {Constructor@2150} "public com.healingpaper.payment.domain.payments.Test1()"
constructors2 = {Constructor[2]@1889} 
 0 = {Constructor@2145} "public com.healingpaper.payment.domain.payments.Test2(long)"
 1 = {Constructor@2146} "public com.healingpaper.payment.domain.payments.Test2()"

```

**Comment by nallwhy** [comment]
방향이 맞다면 `autoparams-kotlin` 에 `KotlinCustomizer` 를 제가 만들어 볼 수도 있지 않을까라는 생각을 허허

**Comment by gyuwon** [comment]
아하 그렇군요. 그럼 #66 의 4번으로 해결될 수도 있겠네요.

**Comment by nallwhy** [comment]
no arguments constructor 로 인해 생기는 이슈는 해결될텐데 secondary constructors 이슈는 별도로 해결해야하지 않을까 싶기도 하네요 ㅎㅎ

Java 와 달리 명확한 선호가 있는 것이라서

**Comment by gyuwon** [comment]
@nallwhy 오랜시간 논의가 이어지지 않아 이 이슈는 일단 닫겠습니다. 필요하시면 다시 열어주세요. :)
