### ISSUE TITLE
라벨 규칙

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#24]
논의 중 이슈 -> question 라벨
기능 구현이 확정된 이슈 -> <s>feature</s> enhancement 라벨
버그로 확인된 이슈 -> bug 라벨
아직 내용 파악이 안된 이슈 -> 무 라벨

현재 어떤 이슈가 채택된 것인지 어떤 이슈가 논의 중인지 잘 안보여서, 이런 식의 라벨 규칙이 있으면 좋을 것 같습니다.

**Comment by gyuwon** [comment]
좋습니다. 레이블 달겠습니다.

**Comment by jwChung** [comment]
feature 가 기본 라벨이 아니죠. feature -> enhancement 로 정정합니다.

**Comment by gyuwon** [comment]
@jwChung 확인하고 이슈 닫아주세요.
