### ISSUE TITLE
junit-jupiter-params 5.7.2 지원

### ISSUE THREAD

**Issue by wplong11** [JavaUnit/AutoParams#260]
## 오류 내용

`@CsvAutoSource`를 사용하면 다음과 같은 오류가 발생합니다.

```
Receiver class org.javaunit.autoparams.CsvAutoArgumentsProvider$1 does not define or inherit an implementation of the resolved method 'abstract int maxCharsPerColumn()' of interface org.junit.jupiter.params.provider.CsvSource.
```

## 오류 원인

아래 명령어를 사용하여 의존 그래프를 확인하면, autoparams 패키지는 junit-jupiter-params은 5.7.2 버전을 사용합니다.

```bash
$ ./gradlew <프로젝트명>:dependencies

\--- io.github.javaunit:autoparams:0.2.8
     +--- org.junit.jupiter:junit-jupiter-api:5.6.0 -> 5.7.2 (*)
     +--- org.junit.jupiter:junit-jupiter-params:5.6.0 -> 5.7.2 (*)
     +--- javax.validation:validation-api:2.0.1.Final
     \--- com.google.code.findbugs:jsr305:3.0.2
```

1. javaunit:autoparams는 5.6.0을 사용하도록 설정되어있으나 의도치 않게 5.7.2가 사용됩니다

    https://github.com/JavaUnit/AutoParams/blob/05c33321821b5f660537a996ccad244e1150db68/autoparams/build.gradle#L7

2. junit-jupiter-params 5.7.2 버전에서 `@CsvSource`에 [int maxCharsPerColumn()](https://github.com/junit-team/junit5/blob/27b9841d5b5a64ec6aabd670d495e233f7d93f2e/junit-jupiter-params/src/main/java/org/junit/jupiter/params/provider/CsvSource.java#L109-L119) 메서드가 추가됐지만, AutoParams에서 이를 구현하지 않아 문제가 발생합니다.
   https://github.com/JavaUnit/AutoParams/blob/05c33321821b5f660537a996ccad244e1150db68/autoparams/src/main/java/org/javaunit/autoparams/CsvAutoArgumentsProvider.java#L29-L59

**Comment by gyuwon** [comment]
@wplong11 사용중인 프로젝트에서 `org.junit.jupiter:junit-jupiter-params` 패키지를 `5.7.2`로 별도로 설치하나요?

**Comment by wplong11** [comment]
@gyuwon  사용중인 프로젝트에서 `junit-jupiter-params` 패키지를  직접 설치하지는 않고,
`org.springframework.boot:spring-boot-starter-test:2.5.4` 패키지에 의해 설치되고 있습니다.

이슈 재현한 셈플 프로젝트 첨부합니다. SpringInitializer로 빈 프로젝트 생성하고 AutoParams 의존만 추가했습니다
https://github.com/wplong11/AutoParamsDependencyIssue

**Comment by wplong11** [comment]
AutoParams를 사용하는 프로젝트에서 `junit-jupiter-params` 버전을 강제로 지정하여 해결한 예시도 첨부합니다.
아직 gradle에 익숙하지 않아서 최선인지 잘 모르겠고, 불안한 방법처럼 보입니다.

https://github.com/wplong11/AutoParamsDependencyIssue/pull/1/files

**Comment by gyuwon** [comment]
> https://github.com/wplong11/AutoParamsDependencyIssue/pull/1/files

![image](https://user-images.githubusercontent.com/973743/130342855-8505af3a-e9a0-41b9-b4d5-8789fd93f19f.png)

**Comment by gyuwon** [comment]
`5.6` -> `5.7` 마이너 버전 변경에서 만드는 breaking change는 유쾌하진 않군요.

**Comment by wplong11** [comment]
JUnit 팀에서 `@CsvSource`을 구현하는 시나리오는 고려하지 않고, annotation으로 사용하는 시나리오만 생각해서 breaking change를 발생시킨 것 같네요 :cry:

아니면 `@CsvSource` 구현할 때 default value가 설정된 property는 override하지 않아도 되는 방법이 있으려나요 🤔

**Comment by gyuwon** [comment]
Java를 과대평가 하지 마세요.

**Comment by wplong11** [comment]
https://youtu.be/s9d44ikc02k?t=72
