### ISSUE TITLE
@AutoSource 커스터마이즈 확장 이노테이션에서 repeat 적용

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#272]
아래와 같이 `@DomainAutoSource` 라는 확장 애노테이션을 적용할 경우 repeat 을 적용할 수 없습니다.

https://github.com/JavaUnit/AutoParams/pull/266/files#diff-af32e1fe0d87069ff4e64c431a0db4ae5f25dfb78711c2472b9a2530dc1bdb98R36

repeat 을 변경하고 싶다면 아래와 같이 확장 애노테이션 정의시 고정된 repeat 값만 정의할 수 있습니다.
```java
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Customization(DomainCustomizer.class)
@AutoSource(repeat = 3)
public @interface DomainAutoSource {
}
```

@wplong11 @gyuwon 확장 애노테이션에도 repeat 을 선언하고 적용할 수 있게 지원할 아이디어가 있으실까요?
우선 아래와 같이 선언하면 의도한 대로 동작하긴 합니다.

```java
@ParameterizedTest
@AutoSource(repeat = 3)
@DomainAutoSource
void test() {
}
```

이렇게 할 수 있게 지원할 수 있을지 고민되네요
```java
@ParameterizedTest
@DomainAutoSource(repeat = 3)
void test() {
}
```

**Comment by gyuwon** [comment]
필요하지만 놓친 기능이네요. 저도 방법을 고민해보겠습니다.

**Comment by gyuwon** [comment]
현재 디자인은 `AutoArgumentsProvider` 클래스가 `@AutoSource` 클래스의 `repeat` 속성에 의존하기 때문에 확장하기 아주 어렵네요. 애노테이션 간에는 상속도 이용할 수 없고요.

**Comment by gyuwon** [comment]
현재로선 이렇게 하는 것이 최선이네요.

```java
@AutoSource(repeat = 3)
@Customization(DomainCustomizer.class)
```

**Comment by gyuwon** [comment]
편의성은 현재 모습이 좋은데 `@Repeat` 애노테이션을 도입하는 것이 확장성에는 더 좋다고 보여집니다.
