### ISSUE TITLE
junit5 관련 기능 별도 모듈 분리

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#28]
AutoParams는 현재 junit5에 의존하고 있습니다. 계획한 것으로 이해됩니다만, gradle 멀티 모듈(#19)로 구성된다면 다음과 같은 이유에서 junit5 관련 기능을 별도 모듈로 분리할 것을 제안합니다.

- junit4 지원할 수 있는 확장 포인트가 생김
- junit6 이 나오면  junit5와 함께 병렬지원 가능
- junit 왜 다른 test framework에서 사용가능

**Comment by gyuwon** [comment]
이 프로젝트는 이름부터 jupiter의 `@ParameterizedTest`를 염두에 두고 지어졌습니다. 이후 설계 개선 과정에서 junit5 독립 코드가 잘 분리된다면 이 코드를 새 프로젝트로 분리한 후 AutoParams가 의존하는 방향으로 하는 것이 좋을 것 같습니다. 저는 당분간은 AutoParams가 junit5에 집중하는 것이 좋지 않을까 싶습니다.

**Comment by jwChung** [comment]
이슈 닫겠습니다.
