### ISSUE TITLE
Customization API 공개

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#3]
제공되는 기능만으로는 실무의 다양한 도메인을 반영하는 데이터를 생성하기 어렵다. 결국 각 사용자의 도메인을 반영하는 데이터를 생성할 수 있도록 customization API가 제공되어야 한다.

하지만 customization API는 강력한 기능이기 때문에 breaking change를 막으려면 초기에 깊이 고민하고 설계되어야 한다. 이 이슈에서 customization API와 관련된 아이디어를 수집한다.

**Comment by gyuwon** [comment]
@jwChung @mhyeon-lee 의견 주세요!

**Comment by mhyeon-lee** [comment]
사내에서 만들어서 활용하고 있는 라이브러리에서는 다음과 같은 인터페이스로 Customize 를 구현해서 생성된 객체를 각 도메인 요구에 맞게 값 조정하도록 지원했었습니다.

```java
// 실제 정의는 좀 더 다양한 기능을 제공하고 있지만, 아래는 메인 인터페이스만 적었습니다.
@FunctionalInterface
public interface Customizer<T> {
    T customize(T obj);
}
```

실제 프로젝트에 적용하다 보니, 저것만으로는 원하는 상태의 객체를 만들기에 제한되는 부분이 많아 좀 더 부가 기능들이 들어갔었습니다.

@jwChung 님이 합류하시고, 해당 라이브러리를 re-design 하면서 customization api 를 어떻게 디자인할지 다시 고민해보고 있습니다.

간단한 논의가 되지는 않을거 같으니, 시간이 맞을 때 ZOOM 이나 화상으로 한번 논의 해보면 좋겠다는 생각이 듭니다.

**Comment by gyuwon** [comment]
@kingbbode 님도 같이 논의해보면 좋겠네요.

**Comment by jwChung** [comment]
@kingbbode 엇 용근님 안녕하세요 :)
