### ISSUE TITLE
ObjectGenerationContext.getGenerator -> generate로 변경 

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#30]
`ObjectGenerationContext` 클래스에 아래 메소드를 추가하면 `objectGenerationContext.genearte(query)` 와 같이 바로 사용할 수 있을 것 같은데요.

```java
public Optional<Object> generate(ObjectQuery query) {
    return this.generator.generate(query, this);
}
```

`objectGenerationContext.getGenerator().generate(query, objectGenerationContext)` 이렇게 `objectGenerationContext` 를 지정하는 이유가 있을까요?

**Comment by gyuwon** [comment]
@jwChung `ObjectGenerationContext`는 현재 공개 API가 아닙니다. 그래서 디자인에 크게 신경쓰지 않고있고 공개 전에는 언제든 누구든 디자인을 수정할 수 있습니다. 현재 디자인은 저도 잘 기억나지 않는데 리팩터링 과정에서 남은 잔재가 아닐까 싶어요.

**Comment by jwChung** [comment]
@gyuwon 네 공개 API가 아닌 점은 확인했습니다. 제가 이해하지 못하는 의도가 있나 싶어서 이슈를 열어서 질문드렸습니다.
