### ISSUE TITLE
간헐적으로 Fixture의 값이 모두 null로 생성 됩니다.

### ISSUE THREAD

**Issue by coplayer** [JavaUnit/AutoParams#33]
@WebMvcTest 내부에 테스트에서 간헐적으로 Fixture의 값이 모두 null로 생성됩니다.

**Comment by gyuwon** [comment]
간단한 재현 프로젝트를 만들어 주실 수 있을까요?

**Comment by gyuwon** [comment]
@jwChung @mhyeon-lee 혹시 이런 현상 재현 시도 해주실 수 있을까요?

**Comment by Rebwon** [comment]
버그 재현 레포입니다.
https://github.com/Rebwon/bug-auto-params

![1](https://user-images.githubusercontent.com/31135322/111309551-5fcb1980-869f-11eb-89c4-56925058075d.png)

**Comment by jwChung** [comment]
@Rebwon 님 케이스 경우는 만들려고 하는 타입(생성자) 접근자가 public 이 아니어서 문제가 된 것 같군요.

**Comment by Rebwon** [comment]
@jwChung 접근자 문제는 아닌 것 같습니다. 여전히 같은 동작입니다.

**Comment by gyuwon** [comment]
@jwChung 그 경우에도 `null` 이 생성되면 안되고 예외가 던져져야 하겠네요.

**Comment by jwChung** [comment]
@Rebwon  전 SampleDto 클래스를 public 접근자로 수정하면 잘 되는군요.

![image](https://user-images.githubusercontent.com/3784448/111317635-ade41b00-86a7-11eb-8b9a-36266310756e.png)

**Comment by Rebwon** [comment]
@gyuwon @jwChung 특정하긴 어렵지만, 여러 시도를 해본 결과 @Lombok 문제일 가능성이 있다고 생각됩니다. 코드의 컴파일 과정에서 뭔가 문제가 발생하는 거 같다는 추측을 해봅니다.

**Comment by Rebwon** [comment]
@gyuwon @jwChung final을 붙이지 않아도, 기본적으로 ComplexObjectGenerator의 접근 제어자가 public이면 동작하는 걸 확인했습니다. 다음과 같은 테스트 케이스에서 mvn clean 후 compile을 시도하여 여러번 테스트를 동작시킨 결과, 간헐적으로 100번의 생성이 모두 null이 반환됩니다.

https://github.com/Rebwon/real-world-backend/blob/master/src/test/java/com/rebwon/realworldbackend/modules/member/web/MemberWebMvcTest.java

**Comment by jwChung** [comment]
@Rebwon 전 여러 번 해도 실행해도 재현이 안되네요 ㅜㅜ

@coplayer 조금 더 상세한 정보를 말씀해주시면 도움이 될 것 같아요.

**Comment by Rebwon** [comment]
@jwChung 재현되고 있는 제 로컬머신에 환경은 다음과 같습니다.

- Windows10
- OpenJdk 11.0.10_9
- Intellij 2021.1 beta
- maven 3.6.3

![1](https://user-images.githubusercontent.com/31135322/111391758-9aad6b80-86f8-11eb-806b-249525e57930.png)
![2](https://user-images.githubusercontent.com/31135322/111391761-9c772f00-86f8-11eb-8533-40f03d24fd5d.png)

**Comment by mhyeon-lee** [comment]
@gyuwon @jwChung @Rebwon 
자세히 보지는 않았는데요. RegisterRequest 에 생성자가 2개네요
`@NoArgsConstructor`, `@AllArgsConstructor`
```java
@JsonRootName("user")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class RegisterRequest {
}
```

`ComplexObjectConstructorResolver` 에서 findFirst 로 생성자가 선택되기 때문에 어떤 생성자가 선택될지 알 수 없습니다.
아마도 `@NoArgsConstructor` 가 선택됐을 때 빈 객체로 객체가 생성되어 속성들이 null 인 객체가 생성됐을거라 생각합니다.
https://github.com/JavaUnit/AutoParams/blob/main/autoparams/src/main/java/org/javaunit/autoparams/ComplexObjectConstructorResolver.java#L12

`@NoArgsConstructor` 를 제거하고 실행해보시겠어요?

**Comment by gyuwon** [comment]
#42 (`@ConstructorProperties` 적용), #43 작업 되면 `0.0.5` 릴리스 하겠습니다. 참고해 주세요. 빠르면 오늘 밤 늦으면 내일 밤이 될 것 같습니다.

**Comment by Rebwon** [comment]
@mhyeon-lee 지적해주신 부분이 맞습니다. 변경하니까 null이 반환되지 않네요.

**Comment by gyuwon** [comment]
Lombok 동작이 간헐적으로 이 오류를 일으킨다면 해당 동작이 결정적(deterministic)이지 않다는 의미군요. 😕

**Comment by coplayer** [comment]
롬복에서 발생하는 에러였군요. 리플 달아주신분들 감사드리고 업데이트 기대하고 있겠습니다.

**Comment by gyuwon** [comment]
@coplayer `0.0.5` 릴리스 되었습니다. https://github.com/JavaUnit/AutoParams/releases/tag/0.0.5 확인 부탁드립니다.

**Comment by coplayer** [comment]
@gyuwon 빠른 픽스 감사 드립니다. 유용하게 활용하겠습니다 👍
