### ISSUE TITLE
병합된 브랜치 자동 삭제 옵션 ON

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#35]
@gyuwon 님 repo settings 에 아래 옵션 키면 어떨까요?
PR Merge 시 branch 를 자동 삭제 합니다.

<img width="960" alt="스크린샷 2021-03-16 오후 10 14 04" src="https://user-images.githubusercontent.com/5206572/111314781-1251ab00-86a5-11eb-8445-c863094c1995.png">

**Comment by gyuwon** [comment]
설정 했습니다!
![image](https://user-images.githubusercontent.com/973743/111315265-8e4bf300-86a5-11eb-953c-55160bb4524a.png)
