### ISSUE TITLE
ObjectGenerator 난수 생성에서 범위를 추가하는 기능이 필요합니다.

### ISSUE THREAD

**Issue by Rebwon** [JavaUnit/AutoParams#4]
안녕하세요 규원님, 좋은 라이브러리를 만들어주셔서 감사합니다.

AutoFixture에 경우 Range를 지정해서 난수를 생성해주는데, AutoParams에서는 Range 기능을 지원하실 생각이 있으신가요?

**Comment by gyuwon** [comment]
물론입니다. 다만 프로젝트 시작한지 아직 일주일 밖에 안돼서 필요한 여러 기능들이 정리되진 않았습니다. 이렇게 이슈를 등록해주시면 저에게 큰 도움이 됩니다!

**Comment by Rebwon** [comment]
넵, 사용해보면서 기여할 수 있는 부분이 있다면 더 많이 기여하고 싶습니다!

**Comment by gyuwon** [comment]
아시겠지만 `RangeAttribute`는 AutoFixture를 위해 존재하는 것이 아니라 기반 라이브러리가 검증 기능을 위해 제공하는 특성인데요, Java에선 이런 역할을 하는 annotation이 있나요? 아님 새로 하나 정의해야 할까요?

**Comment by Rebwon** [comment]
RangeAttribute와 유사한 Java 진영에선 Hibernate Validator에 Range annotation이 존재합니다. https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/Range.html

**Comment by gyuwon** [comment]
@Rebwon `@Range`는 Hibernate API 라서 사용하는 것이 적절하지 않네요. `javax.validation.constraints` 패키지는 JDK에 포함되나요?

**Comment by gyuwon** [comment]
`javax.validation.constraints`는 EE에 있군요.
https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/package-summary.html

**Comment by Rebwon** [comment]
@gyuwon 검증 annotation을 위해서 Java ee 의존성을 사용하는건 아무래도 배보다 배꼽이 큰 상황이라고 생각되어져서, 새로 정의하시는 방향이 좋을 것 같아요.

**Comment by gyuwon** [comment]
@Rebwon 공감합니다.

**Comment by mhyeon-lee** [comment]
JSR380 Bean Validation 2.0 을 의존하는걸 검토해보시면 될거 같습니다.
https://beanvalidation.org/2.0-jsr380/

사내에서 사용하는 라이브러리는 아래 디펜던시를 가지고 지원하고 있습니다.
https://mvnrepository.com/artifact/javax.validation/validation-api

**Comment by gyuwon** [comment]
@mhyeon-lee 저 디펜던시를 메인 패키지(AutoParams)가 가져도 될까요? 아님 AutoParams.Validation 같은 위성 패키지를 만드는 것이 좋을까요?

**Comment by mhyeon-lee** [comment]
JSR 대표 스펙이면서 구현체는 없고 annotation 과 spi 만 가지고 있기 때문에 메인 패키지(AutoParams)가 가져도 괜찮다고 저는 생각합니다.
구현체는 보통 위에서 언급된 [hiberate validator](https://mvnrepository.com/artifact/org.hibernate/hibernate-validator) 가 많이 사용됩니다. (흔히 알고 있는 hibernate orm 과는 다른 패키지 압니다.)

- 포함할 것인지 분리할 것인지는 @gyuwon 님의 방향성에 따라 결정하셔도 좋을거 같습니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 테스트 도구라 의존성 추가가 상대적으로 덜 부담되긴 하죠. @LichKing-lee @Rebwon 두 분 의견은 어떠신가요?

**Comment by Rebwon** [comment]
저 역시 @mhyeon-lee  님과 동일한 의견입니다.

**Comment by LichKing-lee** [comment]
좋습니다 ㅎㅎ

**Comment by gyuwon** [comment]
@mhyeon-lee 많은 분들이 동의하시니 그렇게 결정해요. 우선 의존성만 추가하는 PR을 먼저 만들어주세요.

**Comment by mhyeon-lee** [comment]
`@Nullable` 을 사용한 null 생성도 여기 카테고리에 해당되서 여기에 rerfer 합니다.
https://github.com/JavaUnit/AutoParams/issues/52#issuecomment-800759847

**Comment by gyuwon** [comment]
이 이슈는 `@Min`, `@Max` 애노테이션 지원으로 해결되므로 닫겠습니다.
