### ISSUE TITLE
매개변수 수가 가장 적은 생성자 선택 논리 구현

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#43]
README.md 파일에 다음 문구가 있지만 실제론 구현되지 않는다.

> If the type has more than one public constructors, AutoParams chooses the constructor with the fewest parameters.

**Comment by mhyeon-lee** [comment]
@gyuwon 매개변수가 가장 많은 생성자를 선택하는게 풍부한 속성을 가진 객체를 만드는데 유리할거 같은데 
fewest 로 스펙을 정한데에 고려하신 부분이 있으실까요?

**Comment by gyuwon** [comment]
@mhyeon-lee 생성자가 둘 이상이면 그 중 매개변수가 적은 생성자는 많은 생성자보다 더 많은 도메인 논리를 가진다고 생각했습니다. 적은 생성자는 `this(...);`를 통해 많은 생성자를 호출하며 도메인 논리를 사용해 부족한 인자를 만드는 식인거죠. 그래서 임의성보다는 도메인 논리를 택하는 것이 좋다고 판단했어요.

그런데 말씀하셔서 생각해보니 이유는 잘 모르겠지만 Java 하시는 분들은 lombok을 좋아하고 또 `@NoArgsConstructor`를, 제가 느끼기엔 습관적으로, 많이 사용하던데 그런 경우라면 매개변수가 많은 쪽을 택하는 것이 유리할 수도 있겠네요.

@jaceshim @jwChung 어떻게 생각하세요?

**Comment by mhyeon-lee** [comment]
@gyuwon 
그렇군요 말씀하신거처럼 도메인 논리를 가진 생성자를 직접 작성하는 경우는 매개변수가 적은 생성자를 호출하는게 작성된 도메인 논리들이 실행되겠군요
말씀하신 것처럼 lombok 을 많이 사용하다보니 직접 생성자를 작성하기 보다 롬복에 의한 생성자 자동 생성을 자주 사용하는 경우에는 도메인 논리가 생성자에 없기 때문에 매개변수가 많은 생성자가 유리할거고요

도메인 논리를 가진 생성자를 직접 작성하는 경우에는 `@ConstructorProperties` 로 지정하게 하고,  자동 선택시에는 매개변수가 많은 생성자를 선택하게 하는게 다수의 사용자들에게는 편할거 같다는 생각이 듭니다.

---

`@NoArgsConstructor` 는 습관적으로 넣는 경우도 많고... setter 를 애용하는 개발자들이 넣는 경우도 많고...  JPA 에서 Entity 가 Proxy 로 생성하면서 최소 package-private `@NoArgsConstructor` 를 요구합니다.. ㅠㅠ

**Comment by gyuwon** [comment]
@mhyeon-lee 그런 실정이라면 저도 매개변수 많은 쪽으로 기우네요.

**Comment by jaceshim** [comment]
일반적인 구현시 생성자 선택은 도메인 논리에 따라 적합한 생성자를 선택하겠지만
`AutoParam`의 경우 테스트를 위한 개체를 자동으로 만들어 주는게 주 목적이기에 매개변수가 많은 생성자를 통해 개체를 생성해주는게 라이브러리를 이용하는 사용자들 목적에 부합하는게 아닐까 싶어요...

**Comment by jwChung** [comment]
저는 매개변수가 적은 쪽에 한 표입니다.

- AutoParams가 만들지 매개변수 값을 만들지 못하는 문제를  줄일 수 있고, 
- 대부분의 경우 매개변수가 적은 것은 기본 값으로 설정이 될 텐데요. 기본 값은 AutoParams가 만드는 임의의 값보다 문제 영역에  맞는 값이라 생각됩니다.
- `@NoArgsConstructor` 과 setter 이용으로 invariant를 해치는 문제는 AutoParams에서 직접 다루기보다 사용자가 package-private `@NoArgsConstructor`를 만들거나, 앞으로 만들어질 customization 기능을 사용할 수 있을 거라 생각됩니다.

**Comment by gyuwon** [comment]
@jwChung @mhyeon-lee @jaceshim `@NoargsConstructor(AccessLevel.PROTECTED)` 사용을 가정하고 공용 생성자 중 매개변수가 적은 선택을 하는 것이 저도 바람직해 보이는데 사용자에게 이 가이드를 런타임에 주려면 어떻게 해야 할까요?

그러니까 예를 들어 어떤식으로든 매개변수가 없는 생성자와 있는 생성자가 있다면 AutoParams는 전자를 택할 텐데 이게 프레임워크에 의해 강제된 경우 package-private으로(이게 `AccessLevel.PROTECTED` 맞죠?) 변경하는 것이 좋다는 안내를 담아 예외를 발생시키면 좋을 것 같은데요.

저는 AutoParams가 Java 프로그래머들에게 조금이라도 나은 디자인을 안내할 수 있으면 좋겠습니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 둘 다 고려할 수 있겠네요. 저는 전자 쪽이 약간 더 마음에 듭니다. @jwChung @jaceshim 의견 부탁드립니다.

**Comment by jwChung** [comment]
> Constructor 목록을 얻어왔을 때 N 개이고, 그 중 매개변수가 없는 생성자의 modifier 를 검사했을 때 public 일 경우 안내와 함께 에러를 내면 될거 같아 보입니다.

특정 프레임워크를 사용하지만 public 생성자를 의도할 수도 있을 것 같네요. 

이 기능을 위해선 특정 프레임워크에 의존해서 검사를 해야겠네요.  이 이슈는 먼저 처리하고 런타임 가이드는 따로 고민해보면 어떨까 합니다.

**Comment by gyuwon** [comment]
그럼 다른 의견 없으시면 이 이슈로는 가장 적은 매개변수 선택 논리 반영으로 마무리하고 기본 생성자 문제는 별도의 이슈로 논의하겠습니다.
