### ISSUE TITLE
protected, package-private 생성자 지원 논의

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#47]
@jwChung 님이 아래에서 package-private 생성자 언급을 하셔서 이슈로 남깁니다.
https://github.com/JavaUnit/AutoParams/issues/43#issuecomment-800736377

protected 나 package-private 생성자는 지원하지 않고 public 만 선택되도록 지원할 것인가?
만약 그렇다면 public 생성자가 불필요한 클래스도 AutoParams 를 사용하기 위해서는 public 으로 공개해야 하는게 가이드 방향성이 될 것인가?

**Comment by gyuwon** [comment]
개체 생성은 공개된 생성자나 팩토리 함수를 통하는 것을 원칙으로 봅니다. 그래서 저는 package-private 생성자 지원이 아니가 public 팩토리 함수 지원을 고민해야 하지 않을까 싶어요.

**Comment by jwChung** [comment]
저도 규원님과 같은 생각인데요. 테스트는 공개된 API를 통해서 인스턴스를 만드는게 맞다고 생각해요.

@mhyeon-lee 혹시 non public 생성자를 통해 인스턴스를 만들어야 하는 경우가 있을까요?

**Comment by mhyeon-lee** [comment]
@gyuwon @jwChung 
몇가지 생각나는 케이스들을 적어 보겠습니다.

1. JPA 의 Entity 는 복원을 위해 `NoArgsConstructor` 가 필수로 필요하지만, DB 조회만(Read-Only) 하는 클래스는 사용자가 `NoArgsConstructor` 또는 다른 생성자들을 public 으로 공개하지 않을 수 있습니다.
2. JSON 응답을 Jackson 으로 Deserialize 할 때 선택되는 생성자는 package-private 도 지원하기 때문에, Deserialize 에만 사용되는 클래스는 생성자를 public 으로 공개하지 않을 수 있습니다.
3. 객체 생성을 위해 lombok 의 `@Builder` 를 많이 사용하는데, 자동으로 생성되는 Builder 의 `build()` 메소드는 `AllArgsConstructor` 를 호출하는데  package-private 에서 접근합니다. 그래서 `@AllArgsConstructor` 를 직접 호출하지 않도록 package-private 으로 만들기도 합니다. @gyuwon 님이 팩토리 함수를 지원하는 것을 이야기한것처럼 lombok 의 `@Builder` 를 지원하는 방향도 있습니다. (사내에서 만든 라이브러리에서는 `@Builder` 를 지원합니다.)

위와 같이 객체를 직접 생성하지 않는 클래스는 생성자를 직접 사용하지 않는 경우들이 있는데 이들을 지원할지 여부가 될거 같습니다.
public 만 지원한다면 AutoParams 를 사용하기 위해 생성자를 public 으로 전환하거나 팩토리 생성자를 직접 만들어줘야 할거 같습니다.

다수가 사용하는 특정 라이브러리나 프레임워크의 매직(?)에 의존되는 부분을 지원할 것인가? 하지 않고 조금 불편하지만 기본 원칙을 지키는 방향으로 가이드를 할 것인가? 는 자바 라이브러리를 개발하면서 항상 고민되는 부분이었던거 같습니다.

**Comment by gyuwon** [comment]
F**king magicians!

**Comment by jwChung** [comment]
@mhyeon-lee 설명 감사합니다.

우선 제가 드는 생각은 public API를 기본으로 하고 1/2/3번과 같은 경우가 빈번하다면, 확장 API 공개 수준을 넘어 확장 기능을 구현해서 제공하는 방향으로 가면 어떨까 합니다. 기본적으로 on되어 있는 기능은 아니지만 필요하면 사용자가 on해서 사용할 수 있도록 말이죠.

**Comment by mhyeon-lee** [comment]
@gyuwon 님도 비슷한 의견으로 여기고 이 이슈는 close 합니다.

**Comment by nallwhy** [comment]
public 한 API 로서의 생성자와 테스트 데이터를 만들기 위한 생성자는 다를 수 있다고 생각합니다

명확히 하자면 API 가 아닌 별도의 생성자를 테스트에서 전능하게 사용할 수 있어야 한다고 생각하는데 어떤 방식으로 구현이 가능할지는 모르겠네요

repository 테스트를 할 때 테스트용 데이터를 생성하는 함수는 repository 의 함수를 사용하지 않는다 같은 느낌이랄까

**Comment by gyuwon** [comment]
@nallwhy 의견 고맙습니다.

저는 다른 의견을 가지고 있습니다. 테스트는 클라이언트고 다른 클라이언트와 동일한 조건에서 동작해야 합니다. 수동 테스트를 생각해보죠. QA 담당자가 모바일 앱을 테스트 하기 위해 데이터베이스에 관리자 권한으로 접근해 데이터를 조작한다면 그 테스트는 쓸모있는 결과를 만들지 못할겁니다. 테스터는 최대한 일반 사용자의 입장이 되어야 합니다.

자동화된 테스트 케이스 역시 마찬가지 입니다. 테스트 케이스는 클라이언트 코드고 다른 클라이언트 코드와 동일한 조건에서 동작하는 것이 원칙입니다. 그렇지 않으면 [거짓 음성(false-negative)](https://en.wikipedia.org/wiki/False_positives_and_false_negatives#False_negative_error)을 야기할 수 있으며, 테스트 케이스가 SUT의 숨겨진 정보(design decision)를 알게 되고 또 사용하게 되어 두 모듈 사이에 [내용 결합(content-coupling)](https://en.wikipedia.org/wiki/Coupling_(computer_programming)#Content_coupling)이 발생합니다.

이런 결합이 생기면 SUT 리팩터링이 테스트를 깨지게 만들고 이 비용으로 인해 프로그래머는 리팩터링을 주저하거나 테스트 작성을 꺼리게 되어 결국 단위 테스팅이나 TDD를 실패로 이끕니다. TDD와 관련해 정말 많이 질문받는 것 중 하나가 리팩터링 할때마다 테스트를 고쳐야 한다는 거에요. 사실은 테스트가 있기 때문에 리팩터링을 자유롭고 자신감있게 진행해야 하는데 말이죠. 리팩터링 때문에 테스트를 한 글자라도 바꿔야 한다면, 그건 리팩터링이 아니라 API 디자인 변경이거나 SUT와 테스트가 결합되었기 때문입니다. 이건 비단 TDD에만 문제가 아니라 시스템 디자인에도 치명적입니다.

Repository를 테스트할 때 repository나 repository 의존성의 non-public 인터페이스를 사용하는 테스트가 있다면 이것은 API 디자인 결함의 신호입니다. 테스트는 전능하면 안됩니다. 다른 모든 클라이언트와 동등한 입장이어야 합니다.
