### ISSUE TITLE
JaCoCo 설정

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#50]
Java Code Coverage Library 인 JaCoCo 설정 여부를 논의합니다.
https://www.eclemma.org/jacoco/

- 테스트 커버리지 리포트가 필요한가?
- JaCoCo 를 적용한다면, 결과 리포트 화면 출력을 Github Actions 와 어떻게 연동해야 하나?

**Comment by gyuwon** [comment]
저는 테스트 되지 않은 PR은 승인하지 않을거라 필요 없지 않을까 싶습니다. 😂

**Comment by mhyeon-lee** [comment]
동의합니다. @jwChung 님도 다른 의견 없으시면 close 하겠습니다.

**Comment by jwChung** [comment]
@mhyeon-lee 네 저도 선택사항인 것 같아요.
