### ISSUE TITLE
CharacterGenerator 구현

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#51]
`char`/`Character` 값 생성 기능을 구현합니다. 예상 테스트 시나리오는 다음과 같습니다.

```java
@ParameterizedTest
@AutoSource
void sut_correctly_generates_characters(char char, Character character) {
    assertThat(character).isNotNull();
}
```

**Comment by jwChung** [comment]
@gyuwon 구현이 안된 기능 같아서 이슈 만들었습니다. 확인하신 후 question -> imporvement 라벨 부착 부탁드리겠습니다.

**Comment by sogoagain** [comment]
이슈에 Assignees가 따로 지정되어 있지 않은 것 같아 작업하여 #57 PR을 생성하였습니다.
