### ISSUE TITLE
@Nullable 컨벤션 논의

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#52]
- null 이 반환 가능하거나, null 이 파라미터로 들어올 수 있는 대상에 `@javax.annotation.Nullable` 을 선언하는 컨벤션에 대해 논의합니다.
- `@Nullable` 이 선언된 반환 값을 검사 없이 사용하거나, `@Nullable` 이 선언되지 않은 파라미터에 null 을 넘기면, SpotBugs 에서 NPE 가능성을 분석하고 레포트합니다.
- 추가로 kotlin 에서 java library 를 사용할 때 `@Nullable` 이 붙은 대상은 `?` 로 타입 추론 및 컴파일 지원 합니다.

---

`@Nullable` 컨벤션에 동의가 되면 아래 JSR 305 라이브러리 의존성을 추가합니다.
https://mvnrepository.com/artifact/com.google.code.findbugs/jsr305

**Comment by mhyeon-lee** [comment]
`@Nullable` 은 다음과 같이 지원될 수도 있을거 같군요

```java
@ParameterizedTest
@AutoSource
void sut_correctly_generates_characters(@Nullable Integer value) {
    // value 는 null 이 될 수도 있다.
}
```

**Comment by gyuwon** [comment]
`@Nullable` 수식된 매개변수의 정의역에 `null`을 포함시킬지 여부를 말씀하시는 거죠?

**Comment by jwChung** [comment]
우리가 코딩할 때는 NPE 방어 구문을 작성하지 않아도 되서 사용하면 좋을 것 같습니다.

AutoParams의 값 생성에 기능으로 본다면 non-null 값 또는 null 값을 임의로 만들어 주는 기능이 되겠네요. @Range({1,10}) 이런 유효 값 범위 지정 기능으로 생각할 수 있겠네요.

**Comment by mhyeon-lee** [comment]
@gyuwon 
제가 2가지 이슈를 던졌군요

1. 코드 내부 정적 분석 용으로 `@Nullable` 을 선언한다.
2. AutoParams 의 값 generate 시 null 을 포함시킬지 여부를 @Nullable 로 알려준다.

**Comment by gyuwon** [comment]
@mhyeon-lee 그럼 이 이슈로는 1번만 다루고 2번은 별도의 이슈로 분리하면 어떨까요?

**Comment by mhyeon-lee** [comment]
넵 본 이슈의 의도는 1번에 대한 내용이었으므로 이 이슈는 1번만 다루겠습니다.

**Comment by jwChung** [comment]
이슈가 확정이 된 것 같아서 **enhancement** 라벨 붙였습니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 할당해 드렸습니다 ㅎㅎ
