### ISSUE TITLE
기본 생성자 런타임 피드백

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#56]
클래스가 매개변수가 없는 기본 생성자를 포함해 여러 개의 공개(public) 생성자를 가질 때 #43 논리에 의해 기본 생성자가 선택되는데, 프레임워크에 의해 기본 생성자가 유도된 상황이라면 AutoParams가 기본 생성자를 선택하는 것은 바람직하지 않을 수 있다.

이 때 런타임 피드백(예외)를 제공할 필요가 있는지 논의할 필요가 있다.

**Comment by mhyeon-lee** [comment]
공개된 매개변수가 없는 생성자를 사용하는게 나쁘다고 생각되면 예외에 권장 가이드를 주는것도 좋을거 같습니다.

하지만, 공개된 매개변수가 없는 생성자는 프레임워크에 의해 강제된 경우도 많고, (기본 생성자 + setter 요구)
단순하게 사용하는 경우도 있어서 예외를 던지지 않고 빈 객체가 생성되도록 하는 옵션도 이후에 추가되면 좋을거 같습니다.

---

setter 를 요구하는 mybatis, modelMapper 도 정확하진 않지만 NoArgsConstructor 를 요구할거 같습니다.

**Comment by LichKing-lee** [comment]
다양한 이유로 기본 생성자를 사용하게될텐데 이때 테스트 코드에서 예외를 발생시키게되면 사용하는 입장에서 꽤나 큰 허들이 될것 같습니다. 테스트 코드에 사용할 데이터를 자동으로 만들어준다는 편리함때문에 선택했는데 다른 부분에서 불편함을 주게되면 이 라이브러리를 사용해야할 필요성이 줄어들게되지않을까 싶은 생각이 듭니다.

**Comment by jaceshim** [comment]
AutoParam을 사용하는 개발자들은 이를 production code에서 사용하려고 하는게 아닌 Test시 편리한 fixture 생성을 위해 사용하는 만큼
너무 tight한 제약은 오히려 이를 사용하는 사용자들로 하여금 불편함을 증가 시키는 요인이 될 수 있을거란 생각이 듭니다.
제약사항들은 AutoParam이 지속적으로 발전해 나가면서 많은 usecase에 대응하다보면 자연스레 도출되지 않을까 싶습니다

**Comment by gyuwon** [comment]
그럼 그냥 공개 기본 생성자를 선택하도록 현재대로 두는 것이 좋을까요?

**Comment by jwChung** [comment]
네 제 생각도 현재 그대로 두고, **setter를 이용해 자동 값을 넣어 주는 기능**과 **파라메타가 많은 생성자를 선택할 수 있는 기능**같은 걸 지원해준다면 사용자가 알아서 잘 쓸 수 있을 것 같습니다.

그리고 [@mhyeon-lee 님이 말씀하신 시나리오](https://github.com/JavaUnit/AutoParams/issues/47#issuecomment-800749564)를 보면 non-public 생성자를 사용해서 인스턴스를 만드는 기능도 필요할 것 같습니다.

**Comment by LichKing-lee** [comment]
사용자 입장에서는 기본생성자가 존재하여 모든 필드가 null 로 들어오는것도 만족스럽지는 않을 수 있다고 생각되는데요.

기본생성자가 존재하여 기본 생성자로 생성되는 경우 javabeans 에 따라 setter 가 존재한다면 setter 를 이용해 필드를 채워주는 방법이 있을것 같습니다.(jackson 이 이런식으로 동작)

아니면 만족스러운 방법은 아닐 수 있겠지만 setter 유무랑 상관없이 모든 필드는 null을 허용하지않는다! 라는 기조하에 리플렉션을 이용할 수도 있을것같네요.

**Comment by LichKing-lee** [comment]
사용자 입장에서는 기본생성자가 존재하여 모든 필드가 null 로 들어오는것도 만족스럽지는 않을 수 있다고 생각되는데요.

기본생성자가 존재하여 기본 생성자로 생성되는 경우 javabeans 에 따라 setter 가 존재한다면 setter 를 이용해 필드를 채워주는 방법이 있을것 같습니다.(jackson 이 이런식으로 동작)

**Comment by mhyeon-lee** [comment]
@jwChung @LichKing-lee 
논의가 확장되는거 같아 객체 생성 전략에 대한 논의는 #66 를 새로 만들었습니다.

현재 AutoParams 의 객체 생성 기본 전략은 생성자 선택인데 
위에서 다른분들이 의견 주신것 처럼 JavaBeans 스펙에 따른 객체 생성 전략을 선택할 수 있는 옵션이 있다면
기본 생성 전략에서는 NoArgsConstructor 를 선택하지 않거나 에러를 내도 괜찮을거 같습니다.

**Comment by gyuwon** [comment]
그럼 이 이슈는 닫고 @mhyeon-lee 님이 만들어주신 이슈에서 더 논의하는 걸로 하겠습니다. :)

**Comment by jwChung** [comment]
@mhyeon-lee 님은 이슈를 분리하고 싶으신 것 같네요. 이 이슈는 아직 해결되지 않았습니다. 제가 다시 열도록 할께요. :)

**Comment by gyuwon** [comment]
@jwChung 그렇군요 제가 이해력이 부족해서 ㅋㅋ

저는 많은 분들이 기본 생성자에 대한 런타임 피드백이 없는 쪽이 낫다는 의견을 주셔서 이 부분은 변경하지 않고 둬도 괜찮을 것 같습니다.

**Comment by jwChung** [comment]
@gyuwon 네 ㅋㅋ 좀 더 논의해보면 좋을 것 같습니다.

> 기본 생성 전략에서는 NoArgsConstructor 를 선택하지 않거나 에러를 내도 괜찮을거 같습니다.

@mhyeon-lee 님이 지적하는 경우가 아래와 같은 `ComplexObject`가 맞을까요? 이 경우라면 `ComplexObject()` 기본 생성자가 의도된 것인지 유도된 생성자인지 판단이 어렵울 것 같습니다.

```java
public class ComplexObject {
    private int value1;
    private String value2;
    private UUID value3;

    public ComplexObject() {
    }

    public ComplexObject(int value1, String value2, UUID value3) {
        this.value1 = value1;
        this.value2 = value2;
        this.value3 = value3;
    }

    public int getValue1() {
        return value1;
    }

    public String getValue2() {
        return value2;
    }

    public UUID getValue3() {
        return value3;
    }

}
```

**Comment by jwChung** [comment]
#43 와는 반대로 **생성자 매개변수가 가장 많은 걸 선택**하면 이 문제는 해결될까요? 그럼 수정해서라도 이렇게 가는게 좋을 것 같습니다.

기본 전략은 심플해서 직관적이었음 좋겠습니다. 기본 전략이 맞지 않는 경우는 사용자가 전략을 선택할 수 있게 해주면 될 것 같습니다.

**Comment by mhyeon-lee** [comment]
@jwChung 
개인적인 생각으로 매개변수가 없는 기본 생성자를 호출해서 모든 속성이 null 인 객체를 생성하고자 하는 사람은 거의 없을거 같다고 생각됩니다.
위 가정을 차용 한다면 저희는 다음의 선택을 검토할 수 있습니다.

1. 에러를 던지고 `@ConstructorProperties` 를 생성자에 지정하도록 가이드 한다.
2. 기본 생성자를 선택해서 모든 속성이 null 인 객체를 반환하되 log.warn 으로 `@ConstructorProperties` 를 지정하도록 가이드 한다.
3. 기본 생성자를 제외한 fewest 생성자를 선택한다. 만약 기본생성자가 의도된 것이라면 기본생성자에`@ConstructorProperties` 를 붙인다.
4. 임의의 값을 생성하는 것처럼 공개된 생성자들도 각각의 사용자 시나리오로 판단. 임의의 생성자를 선택해버린다.
   - `@ConstructorProperties` 가 있을 때는 해당 생성자를 고정으로 선택한다.

**Comment by mhyeon-lee** [comment]
`AutoFixture` 에서는 어떻게 결정하나요?

**Comment by gyuwon** [comment]
@jwChung 근데 저런 경우 기본 생성자는 도데체 왜 만드는 건가요?

**Comment by gyuwon** [comment]
@mhyeon-lee 제가 기억은 잘 안나고 잠깐 Mark Seemann 빙의 해봤는데 무조건 매개변수 적은 쪽입니다.

**Comment by gyuwon** [comment]
정리된 주제이지만 기본 생성자에 대한 예외 피드백은 이런 경우 바람직 하지 않을 것 같네요.

```java
public class ValueContainerDouble implements ValueContainer {

    private final String value;

    // Create a dummy.
    public ValueContainerDouble() {
        this(null);
    }

    // Create a stub.
    public ValueContainerDouble(String value) {
        this.value = value;
    }

    @Override
    public String getValue() {
        return value;
    }

}
```

**Comment by mhyeon-lee** [comment]
지금 상태를 유지하고 `기본 생성자` 가 아닌 다른 생성자 선택을 원하는 사람은 `@ConstructorProperties` 를 붙이라고 가이드하는게 좋겠군요

**Comment by jwChung** [comment]
@mhyeon-lee 

> AutoFixture 에서는 어떻게 결정하나요?

[ModestConstructorQuery](https://github.com/AutoFixture/AutoFixture/blob/master/Src/AutoFixture/Kernel/ModestConstructorQuery.cs) 로 결정되고요. 사용자가 GreedyConstructorQuery를 선택할 수도 있고 만들어서 쓸 수도 있습니다.

**Comment by jwChung** [comment]
@gyuwon 

> 근데 저런 경우 기본 생성자는 도데체 왜 만드는 건가요?

그래서 예외를 던지자는  대안이 나오는 것 같습니다.


----------------------



https://github.com/JavaUnit/AutoParams/issues/56#issuecomment-802437226 이걸로 정리된 것 같네요. 이슈 닫겠습니다. :)

**Comment by gyuwon** [comment]
@jwChung 
![image](https://user-images.githubusercontent.com/973743/111732782-af852d00-88b9-11eb-92a5-ec7ff60b10fd.png)
