### ISSUE TITLE
gradle test 실행 시 스타일 검사

### ISSUE THREAD

**Issue by gyuwon** [JavaUnit/AutoParams#62]
@mhyeon-lee @jwChung PR 올려주시는 분들이 스타일이 깨지는 커밋을 만드시는 경우가 종종 있습니다. 이후에 스타일 수정 커밋을 만드십니다. 그래서 제가 빌드가 실패하는 커밋이 없도록 리베이스를 요청드리는데요, 아마 커밋 만들기 전에 테스트는 모두 실행하실 것 같으니 `gradle test` 실행 시 스타일 검사를 하도록 하면 어떨까요?

**Comment by mhyeon-lee** [comment]
#63 로 추가했습니다.
spotBugs 까지는 필요 없을까요?

추가로 @gyuwon 님이 merge 하실 때 Squash and merge 로 하나의 commit 으로 병합하셔도 될거 같습니다.
(하나의 PR 이 하나의 작업을 하도록 가이드는 계속 하실거로 생각됩니다.)

![스크린샷 2021-03-18 오전 11 05 49](https://user-images.githubusercontent.com/5206572/111562697-fbf93b80-87d9-11eb-8732-2c557378f4ad.png)

**Comment by gyuwon** [comment]
@mhyeon-lee 하나의 PR이 하나의 주제는 가지되 커밋은 둘 이상이 되어도 괜찮다고 생각해요. 일단은 리베이스 병합을 유지하려고 합니다. 기여자 분들이 너무 힘들어 하신다는 느낌이 들면 고려해 보겠습니다.
