### ISSUE TITLE
ObjectGenerator 인터페이스에 템플릿 메소드 패턴 도입 제안 

### ISSUE THREAD

**Issue by jaceshim** [JavaUnit/AutoParams#65]
`ObjectGenerator` 인터페이스를 구현하는 모든 클래스는 generate를 구현해야 하고
구현은 은닉대상이 맞으나 현재 구현된 모든 Generator가 Object를 생성하기 위해 수행되는 공통 행위는 두가지 입니다.
- 대상 type 확인
- Object 생성

type을 체크하고 factory를 호출하는 이 로직 부분을 `ObjectGenerator` 공개 책임으로 도출하고 
이를 Java에서 제공하는 default method를 통해서 `ObjectGenerator` 인터페이스 내에 Object생성 rule을 일반화 시키는건 어떨까요?
```java
interface ObjectGenerator {

    ThreadLocalRandom RANDOM = ThreadLocalRandom.current();

    default Optional<Object> generate(ObjectQuery query, ObjectGenerationContext context) {
        if (isSuitableType(query)) {
            return factory(query, context);
        }
        return Optional.empty();
    }

    boolean isSuitableType(ObjectQuery query);

    Optional<Object> factory(ObjectQuery query, ObjectGenerationContext context);
}
```

아니면 `ObjectGenerator` 는 현재처럼 유지하되
`AbstractObjectGenerator` 를 도입하여 아래와 같이 처리하는건 어떨까요?

```java
abstract class AbstractObjectGenerator implements ObjectGenerator {

    @Override
    public Optional<Object> generate(ObjectQuery query,
        ObjectGenerationContext context) {
        if (isSuitableType(query)) {
            return factory(query, context);
        }
        return Optional.empty();
    }

    abstract boolean isSuitableType(ObjectQuery query);

    abstract Optional<Object> factory(ObjectQuery query, ObjectGenerationContext context);
}
```

개인적으론 변경의 여파가 적은 후자가 더 좋을것 같습니다.

고견 부탁드립니다.

P.S. 본인은 패턴 빠는 아닙니다. 😇

**Comment by gyuwon** [comment]
저는 구현의 영역 설계 변경은 큰 의견이 없어서 둘 다 괜찮습니다. 다만 지금 개선되는 디자인은 customization API 방향이 결정되면 모두 뒤집어질 수 있습니다. 😅

**Comment by jwChung** [comment]
@jaceshim factory 와 generate 메소드 로직에는 어떤 차이가 있나요? 혹시 factory가 `Optional<Object>` 아닌 `Object`를 반환을 의도하셨을까요?

**Comment by jaceshim** [comment]
@jwChung 로직의 차이는 없습니다.
다만 모든 Generate 구현체에서 공통으로 행해지는 type check 및 Object 생성 로직을 일반화 시키고
실제 구현체는 generate를 통해서 수행되는 공통 행위 로직은 신경안쓰고 반드시 수행 해야 하는 type check와 Object 생성 로직에 집중? 시키려는 의도였습니다.
근데 customization API 도입으로 인해 전면 Re design이 발생한다면 굳이 도입할 필요는 없을것 같아요~

**Comment by jwChung** [comment]
@jaceshim 의견 감사드립니다.

factory가 `Optional<Object>`가 아니고 `Object` 타입을 리턴하면 다음과 같이 `can + do 스타일`로 표현할 수 있고,

```
// can + do 스타일
boolean isSuitableType(...);
Object factory(...);
```
`boolean + Object = Optional<Object>` 와 같이 하나의 타입으로 쓰면 아래와 같이 `tryDo` 스타일로 쓸 수 있을 것 같습니다.

```
// tryDo 스타일
Optional<Object> generate(...);
```

말씀하신 걸 표현하면 다음과 같이 `can + tryDo 스타일`이 되는데, can 조건이 true 인데 tryDo가 empty를 반환하는 경우도 표현이 되는군요. 이 점은 좋지 않은 것 같습니다.

```
// can + tryDo 스타일
boolean isSuitableType(...);
Optional<Object> factory(...);
```
