### ISSUE TITLE
byte 값 생성 지원

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#69]
`@AutoSource`가 아래 예저 코드처럼 `byte`, `Byte` 형식을 지원하도록 한다,.

```java
@ParameterizedTest
@AutoSource
void test(byte b1, Byte b2) {
}
```

**Comment by gyuwon** [comment]
@mhyeon-lee 아직 제너레이터는 공용 API가 아니니 이슈 제목을 `byte 값 생성 지원` 처럼 바꾸는 것이 어떨까요?
