### ISSUE TITLE
SNAPSHOT 배포

### ISSUE THREAD

**Issue by mhyeon-lee** [JavaUnit/AutoParams#81]
릴리즈 후에 버전 정보를 `{nextVersion}-SNAPSHOT` 으로 바꾸고,

main 에 PR 이 merge 되면 github Actions 에서 SNAPSHOT 을 자동으로 배포해주면 어떨까요?

**Comment by jwChung** [comment]
@mhyeon-lee

1. SNAPSHOT  pre-release 버전을 사용해볼 수 있는건가요?
2. maven에서는 SNAPSHOT 외 다른 pre-release 버전 이름을 사용할 수 없나요? (eg. 1.2.3-alpha)

**Comment by mhyeon-lee** [comment]
@jwChung 
`-SNAPSHOT` 을 붙인 버전은 snapshot repo 로 배포합니다.
snapshot repo 는 같은 버전을 계속 덮어씌워서 배포할 수 있습니다.

말씀하신 pre-release 버전은 원하는 이름으로 release repo 에 배포하면 됩니다.
release repo 에 배포된 버전은 덮어씌울 수 없습니다.

**Comment by gyuwon** [comment]
@mhyeon-lee 혹시 SNAPSHOT 릴리스는 넥서스에서 수동으로 작업해주지 않아도 되나요?

**Comment by jwChung** [comment]
SNAPSHOT 버전은 자동 생성이 필요합니다.  그런데 현재 버전(`0.0.7`)에 `0.0.7-SNAPSHOT` 과 같이 pre-release으로 표현하면,

`0.0.7` > `0.0.7-SNAPSHOT`

의미가되니, GitCommitId을 포함하는 [메타버전](https://semver.org/#spec-item-10 )(`+GitCommitId-SNAPSHOT`) 을 붙이면 좋을 것 같습니다. 

`0.0.7` = `0.0.7+GitCommitId-SNAPSHOT`

> Thus two versions that differ only in the build metadata, have the same precedence.

**Comment by mhyeon-lee** [comment]
@gyuwon SNAPSHOT 은 자동으로 배포할 수 있게 해줘야 할텐데 확인해보겠습니다

0.0.7 릴리즈 후에 0.0.8-SNAPSHOT 으로 커밋해야 될거 같습니다.

**Comment by jwChung** [comment]
@mhyeon-lee 0.0.7에서 버전 증가는 1.0.0, 0.1.0, 0.0.8 이 중 셋이 될 수 있기 때문 메타 데이터가 표현이 어떨까 했습니다. git id를 넣으면 소스와 바이너리를 연결지을 수도 있고 해서요.

> 0.0.7 릴리즈 후에 0.0.8-SNAPSHOT 으로 커밋해야 될거 같습니다.

이유를 여쭤봐도 될까요?

**Comment by mhyeon-lee** [comment]
0.0.7 이후에 0.1.0 이 예정되어 있다면 0.1.0-SNAPSHOT 으로 커밋하면 될거 같습니다.

> 이유를 여쭤봐도 될까요?

0.0.7 이후에 들어온 커밋들은 이미 0.0.7 이후 변경입니다.
그래서 0.0.8-SNAPSHOT 또는 0.1.0-SNAPSHOT 이 좀 더 정확할거 같습니다.

git commit id 가 포함되는건 특정 브랜치의 스냅샷을 받을 수 있기는 하지만, 사용자 측에서 dependency 에 매번 git commit id 를 찾아서 명시해야 되는 경우가 있어 불편한 부분이 있습니다.
단순하게 `0.0.8-SNAPSHOT` 으로 dependency 를 설정하는게 편하긴 합니다.

특정 커밋 부분의 확인이 필요하거나 요청이 있을 때 별도로 해당 commit id 또는 issue id 를 넣어서 배포하는 경우를 많이 본거 같습니다.

---

브랜치 관리로 마이너 / 메이저 버전이 달라지는 부분은 별도의 브랜치로 관리되야 될거 같다고 생각됩니다.
0.0.7 다음 릴리즈가 0.1.0 로 진행되더라도 경우에 따라서 0.0.8 로 backport 릴리즈가 필요할 수도 있습니다.
그래서 다음 릴리즈가 0.1.0 이 계획되어 있어 0.1.0-SNAPSHOT 이 나가더라도 0.0.8-SNAPSHOT 도 필요할 수 있습니다.

---

위에서 제가 언급한 방식들은 Spring 이나 다른 Java 라이브러리에서 많이 선택하는 버전 및 브랜치 관리 방법을 참고해서 말씀드렸습니다.
혹시 .NET 의 오픈소스 라이브러리 들에서는 다른 방법으로 관리하는지 궁금합니다.

절대적인 방법이 있는건 아니니 더 나은 방법이 있으면 정해서 진행하면 될거 같군요

**Comment by jwChung** [comment]
@mhyeon-lee

1. 컷밋이라고 하시는게, 버전 변경 git 커밋아니고 SNAPSHOT 배포를 말씀하시죠?
2. 0.0.7 에서 자동으로 버전을 결정행할텐데, 패치 버전을 올리는 자동 방식이라면 다음 정식 배포 버전 이전까지는 0.0.8-SNAPSHOT 에 계속 덮어써지겠군요. SNAPSHOT 특정 컷밋에서 발생하는 이슈를 다운 받아서 재현해볼  수 있다는 장점을 전 생각했습니다.
   > git commit id 를 찾아서 명시해야 되는 경우가 있어 불편한 부분이 있습니다.
   
   git log에 보이는 정도의 컷밋 id 길이를 사용하면 되지 않을까 합니다. [현재 버전](https://github.com/JavaUnit/AutoParams/blob/main/build.gradle#L19)에 log에 보이는 컷밋 id를 붙이면 될 것 같습니다.

-----------------------------------------

> 혹시 .NET 의 오픈소스 라이브러리 들에서는 다른 방법으로 관리하는지 궁금합니다.

닷넷에서는 SNAPSHOT과 같이 지정된 라이브러리 리포지토리는 없습니다. 대신 개인이 라이브러리 리포지토리를 만들어가 이를 지원하는 My Get 같은 서비스를 이용할 수 있습니다. 그외엔 pre-release 버전을 지원하는 것이랑 다른 건 별반 차이가 없는 것 같습니다. /cc @gyuwon 

-----------------------------------------

서비스가 아니 라이브러리라서  SNAPSHOT 버전을 배포하면 만들면 얼마나 쓸까 싶긴 합니다. ㅋㅋ @mhyeon-lee 어떤 시나리오서 많이 사용할까요?

**Comment by mhyeon-lee** [comment]
@jwChung 말씀을 들어보니 SNAPSHOT 버전에 대한 지속적인 자동 배포를 할 것인가, 필요한 경우에만 배포할 것인가 에 따라 달라지겠군요

저는 지속적인 자동 배포 관점에서 main 에 merge 될 때마다 최신 main branch 가 배포되는 경우를 가정해서 의견을 드렸고,
@jwChung 님의 경우는 아래와 같은 bug fix 부분을 릴리즈 전에 사용자에게 확인 용도로 제공하기 위한 방법을 생각한거로 해석됩니다.
(https://github.com/JavaUnit/AutoParams/issues/33#issuecomment-801152436 에서 릴리즈 전에 SNAPSHOT 을 배포해서 확인)

SNAPSHOT 지속 자동 배포 는 이후에 필요성이 제기됐을 때 다시 검토해도 될거 같습니다.

---

> 서비스가 아닌 라이브러리라서 SNAPSHOT 버전을 배포하면 얼마나 쓸까 싶긴 합니다. ㅋㅋ @mhyeon-lee 어떤 시나리오에서 많이 사용할까요?

AutoParams 를 의존하는 다른 라이브러리가 있다면 유용할 것입니다. AutoParams 가 릴리즈 되지 않았더라도 변경 사항에 대한 대응을 동시에 진행할 수 있습니다. (AutoParams 가 릴리즈된 후에 변경 반영을 진행하면 느린 경우들이 있습니다.)

제가 관리하는 [Spring JDBC Plus](https://github.com/naver/spring-jdbc-plus) 는 Spring Data JDBC 를 의존하고 버전을 같이 맞추고 있는데요 SNAPSHOT 을 의존하면서 변경사항을 대응하고, 가능한 릴리즈 주기를 맞춥니다.
(최근에는 바빠서 빨리 못 따라 가고는 있습니다.)

**Comment by mhyeon-lee** [comment]
@jwChung 
1. 컷밋이라고 하시는게, 버전 변경 git 커밋아니고 SNAPSHOT 배포를 말씀하시는 거죠?
    - 버전 변경 git 커밋이 맞습니다. 
    - 이런 커밋을 참고할 수 있습니다. https://github.com/spring-projects/spring-data-jdbc/commit/087544926fa321128505a8ac6804d2d094feeb4b

2. 1번에서 직접 커밋했기 때문에 자동으로 버전을 결정하는건 아니겠네요

**Comment by jwChung** [comment]
@mhyeon-lee 아 이해했습니다. 말씀하신 SNAPSHOT 배포는 정식 배포 전에 main 브랜치에 반영된 기능/버그개선을 사용하기 위한 용도군요.

maven 배포를 다음과 같이 4가지로 나눈다면,

1. 1.2.3-beta.4-SNAPSHOT: A snapshot version of a pre-release version.
1. 1.2.3-SNAPSHOT: A snapshot version of a release version.
1. 1.2.3-beta.4: A stable version of a pre-release version.
1. 1.2.3: A release version (which is a stable, non-snapshot version, obviously).

닷넷에서 말씀하신 용도의 경우,  3번 pre-release 기능을 이용합니다. 자바(maven repo)도 SNAPSHOT 배포대신 3번을 택할 수 있을 것 같은데 관습이 다른 것 같군요. 닷넷의 경우는 3번 방식(pre-release)으로 배포하면, 클라이언트에서 pre-release 필터를 ON하지 않으면 참조(다운) 가능 목록에 보이지 않습니다.

**Comment by jwChung** [comment]
@gyuwon 님이 배포하시는 현재의 스타일을 봤을 때(지속적이다 못해 즉각적이군요 ㅋㅋㅋ), @mhyeon-lee 님이 말씀하시는 정식 배포 사이의 간격은 거의 발생하지 않을 것 같군요. 거의 100%  테스트 커버리지를 바탕으로, 바로바로 배포하는 방식이 저도 좋은 것 같습니다.

**Comment by mhyeon-lee** [comment]
@jwChung 넵 우선 지금은 필요하지 않은거 같아 이슈 닫겠습니다 ㅋ
