### ISSUE TITLE
builder fix 기능 구현

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#84]
아래 시나리오와 같이 특정 타입 범위 안에서 값을 고정 시키는 기능을 구현한다. 

이 이슈는 특정 타입 범위란 점에서 #15(테스트 메소드 범위)와 차이를 보이며, #3 custom API 의 사용자 시나리오이다.

```java
@ParameterizedTest
@AutoSource
public void test(Builder<Bar> barBuilder) {
    Bar bar = barBuilder.fix(int.class, 123).build();

    // bar.value == 123
    // bar.getFoo().getValues() == [123, 123, 123]
}

public class Foo {
    private final int[] values;

    public Foo(int[] values) {
        this.values = values;
    }

    ...
}

public class Bar {
    Foo foo;
    int value;

    public Bar(Foo foo, int value) {
        this.foo = foo;
        this.value = value;
    }

    ...
}

```

**Comment by gyuwon** [comment]
`fix` 연산에서 `int.class`와 `Integer.class`는 호환되는 것이 적절할까요?

**Comment by jwChung** [comment]
@gyuwon ja린이 자송합니다, 원시 타입에 대한 class 표현(`int.class`)이 안되는 줄 알았습니다.  int.class, Integer.class 호환문제는 별개의 이슈인 것 같네요. 본문 코드 수정했습니다.(Integer.class -> int.class)

**Comment by gyuwon** [comment]
@jwChung 그럼 `List<Integer>`가 있으니 이렇게 되어야 할 것 같아요.

```java
Bar bar = barBuilder.fix(int.class, 123).fix(Integer.class, 123).build();
```

**Comment by jwChung** [comment]
@gyuwon  `List<Integer>` 는 -> `Foo` 타입으로 수정했습니다. :)

**Comment by gyuwon** [comment]
@jwChung @mhyeon-lee 코딩 들어가기 전에 `Builder<T>` 형식에 대한 디자인이 확정되어야 겠네요. 현재는 `fix` 메서드와 `build` 메서드가 보이고, 인터페이스가 될지 클래스가 될지도 결정해야 하고요.

**Comment by gyuwon** [comment]
인터페이스가 좋을 것 같긴 한데 처음엔 `final class`로 시작해서 좀 더 설계 확신이 생기면 그 때 인터페이스로 전환하는 것도 고려해 볼만 하네요.

**Comment by mhyeon-lee** [comment]
우선 인터페이스로 표현하면 다음과 같이 될까요?

```java
public interface Builder<T> {
    Builder<T> fix(Class<?> type, @Nullabe Object value);

    T build();
}
```

**Comment by mhyeon-lee** [comment]
@jwChung 
아래처럼 정의하면, Foo 하위의 int 는 영향 받지 않는게 기대되는 결과이겠죠?

```java
@ParameterizedTest
@AutoSource
public void test(Builder<Bar> barBuilder) {
    Bar bar = barBuilder.fix(int.class, 123).fix(Foo.class, new Foo([456] // array)).build();

    // bar.value == 123
    // bar.getFoo().getValues() == [456]
}
```

---

`int[].class` 가 들어오면 아래처럼 되는게 기대되는 결과이겠죠?

```java
@ParameterizedTest
@AutoSource
public void test(Builder<Bar> barBuilder) {
    Bar bar = barBuilder.fix(int.class, 123).fix(int[].class, [456, 789] // array).build();

    // bar.value == 123
    // bar.getFoo().getValues() == [456, 789]
}
```

---

List, Generics 등을 받으려면 token type 이 필요해질거 같은데 이거는 별도로 논의하겠습니다.

**Comment by gyuwon** [comment]
C#이었다면 `fix` 메서드는 인터페이스의 일부가 아니리 확장 메서드로 디자인 하는 것이 바람직할 텐데 Java에서는 어떻게 하는 것이 좋을까요?

**Comment by gyuwon** [comment]
@mhyeon-lee 아... 빌어먹을 타입 토큰은 피해갈 수 없는 건가요.

**Comment by mhyeon-lee** [comment]
확장 메서드가 없으니 fix 및 동작들을 분리한다면 동작에 대한 인터페이스 들을 나누고 조립해야 될 텐데요

```java
interface Builder<T> {
    T build();
}

interface Fixer<B extends Builder<T>, T> {
    B fix(Class<?> type, @Nullable value);
}

interface AutoBuilder<T> extends Fixer<AutoBuilder<T>, T> {
}
```

어떤 디자인이 나을지 확신이 없으니 의견 주신대로 `final class` 로 시작하는게 좋겠군요

**Comment by jwChung** [comment]
@mhyeon-lee 
> 아래처럼 정의하면, Foo 하위의 int 는 영향 받지 않는게 기대되는 결과이겠죠?
> int[].class 가 들어오면 아래처럼 되는게 기대되는 결과이겠죠?

넵 그렇게 되겠네요.

**Comment by gyuwon** [comment]
@mhyeon-lee 네 제가 'final class'로 시작하자고 말씀드린 것은 클라이언트가 해당 클래스를 상속해 버리면 나중에 인터페이스로 변경할 때 breaking change가 발생하기 때문입니다.
