### ISSUE TITLE
테스트에서 package-private 제품코드 접근 방지

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#87]
다음과 그림과 같이 테스트 패키지 이름을  제품 코드랑 구분해서 package-private 제품코드 접근 방지하는 것에 대해 논의를 해보려고 이슈를 만듭니다. 넌센스일까요?

![image](https://user-images.githubusercontent.com/3784448/111898760-4ba26600-8a6b-11eb-9248-7be3f48d233e.png)

@mhyeon-lee 님이 https://github.com/JavaUnit/AutoParams/pull/83#discussion_r598237623 에서 `org.javaunit.autopararms.test` 이름을 얘기해주셨습니다.

**Comment by jwChung** [comment]
우리도 덧에 빠져 있었군요.

![image](https://user-images.githubusercontent.com/3784448/111898865-f6b31f80-8a6b-11eb-9d0e-c00153d9eb3e.png)

**Comment by mhyeon-lee** [comment]
테스트가 하나의 사용자로서 격리 시킨다면, 의견 주신대로 다른 패키지가 좋겠네요

test 가 사용자이므로, `org.javaunit.autopararms.test` 또는 junit5 이므로, `org.javaunit.autopararms.jupiter` 정도가 떠오릅니다.

**Comment by jwChung** [comment]
@mhyeon-lee "수십 년간 고착된 악습에 대한 거침없는 도전" 을 받아 주시는 것입니까? ㅋㅋ 

`jupiter` 이름도 괜찮네요. 근데 혹시 production에서 사용할 일은 없겠죠? 그래서 전 `test.org.javaunit.autopararms` 이렇게 첫 번째로 붙이는 걸 생각을 했습니다.

**Comment by mhyeon-lee** [comment]
@jwChung 기본 패키지 뒤에 추가로 붙는건 종종 사용해서 `악습에 대한 거침없는 도전` 까지는 아닌거 같은데
시작 패키지가 `test` 로 시작하는건 생소해 보여서 도전으로 보일 수 있을거 같습니다.

production 에서 사용되지 않도록 저희가 제어 해야 될거 같고요

**Comment by jwChung** [comment]
@mhyeon-lee `org.javaunit.autopararms.jupiter` 가 production 코드에 필요하면 테스트에선 `org.javaunit.autopararms.jupiter.jupiter` 이렇게 될테니 문제가 없긴하겠네요.

**Comment by jwChung** [comment]
#88 이 먼저 처리되어야 함.

**Comment by gyuwon** [comment]
`org.javaunit.autopararms.tests` 투척합니다.

**Comment by jwChung** [comment]
@mhyeon-lee  패키지 이름에 단수를  쓴다 혹시 이런 관습이 있습니까? 제가 주로 단수 명사를 본 것 같아서요.

**Comment by mhyeon-lee** [comment]
@jwChung 상관 없을거 같습니다

**Comment by jwChung** [comment]
@mhyeon-lee 그렇군요. 그럼 저도 `org.javaunit.autopararms.tests` 에 한 표 던지겠습니다.

**Comment by gyuwon** [comment]
중요한 건 아니지만 왜 패키지 이름에 단수를 쓸까요? 복수가 직관적인 것 같은데.

**Comment by mhyeon-lee** [comment]
@gyuwon 잘 모르겠습니다.
JDK 패키지가 단수로 되어 있으니 다 단수로 따라가는게 아닐까 싶습니다.

**Comment by gyuwon** [comment]
그럼 저희도 그냥 단수로 갈까요? 단복수 의미가 크게 없다면 컨벤션을 따르는 것도 괜찮을 것 같아서요.

**Comment by jwChung** [comment]
@gyuwon #106 달리셨네요. ㅋㅋ 할당해드렸습니다.
