### ISSUE TITLE
packge-private AutoArgumentsProvider에 접근하는 테스트 수정

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#88]
packge-private 접근자를 가진 [`AutoArgumentsProvider` class를 사용하는 테스트가 여럿 있습니다.](https://github.com/JavaUnit/AutoParams/blob/main/autoparams/src/test/java/org/javaunit/autoparams/AutoArgumentsProviderSpecs.java#L41) 테스트 코드 수정이 필요합니다.

**Comment by jwChung** [comment]
@gyuwon @mhyeon-lee 이거 어떻게 해결하는게 좋을까요?

**Comment by mhyeon-lee** [comment]
접근 제어가 `package-private` 으로 더이상 공개되지 않으니 지워도 되지 않을까요?

**Comment by jwChung** [comment]
@mhyeon-lee: @gyuwon 님이 TDD로 작성하셨을 텐데, 지우면 커버되지 않는 코드가 발생해 회귀검증이 부실해지지 않을까 염려되긴 합니다.

**Comment by jwChung** [comment]
AutoArgumentsProviderSpecs내 테스트를 AutoSourceSpecs 스타일로 모두 변경하는 것은 어떨까요?

**Comment by gyuwon** [comment]
@jwChung 그렇게 할 생각이었어요.

**Comment by jwChung** [comment]
#91 과 이 이슈 @gyuwon 님 할당해드렸습니다.
