### ISSUE TITLE
테스트 클래스 재편

### ISSUE THREAD

**Issue by jwChung** [JavaUnit/AutoParams#91]
테스트 케이스가 많아지면서, 테스트 클래스로 분류하는 작업이 필요합니다. 다음과 같이 값 타입 기준으로 테스트 클래스를 만들어 테스트 케이스를 분류하면 어떨까 합니다.

- `IntergerGenerationSpecs`
- `StringGenerationSpecs`
- `ListGenerationSpecs`
- `CollectionGenerationSpecs`

**Comment by gyuwon** [comment]
`AutoArgumentsProviderSpecs`도 없애버릴 생각입니다. 이 이슈는 저에게 할당해주세요.
